第三十三章

# Exterior Tensor Powers and Exterior Algebras  外张量幂与外代数

## 33.1        Exterior Tensor Powers  33.1外部张量幂

In this chapter we consider alternating (also called skew-symmetric) multilinear maps and exterior tensor powers (also called alternating tensor powers), denoted Vn(E). In many respects alternating multilinear maps and exterior tensor powers can be treated much like symmetric tensor powers, except that sgn(σ) needs to be inserted in front of the formulae valid for symmetric powers.
 在本章中，我们考虑交替（也称为斜对称）多线性映射和外部张量幂（也称为交替张量幂），表示vn（e）。在许多方面，交替的多线性映射和外部张量幂可以被看作是对称张量幂，除了sgn（σ）需要插入到对称幂的有效公式前面。

Roughly speaking, we are now in the world of determinants rather than in the world of permanents. However, there are also some fundamental differences, one of which being that the exterior tensor power Vn(E) is the trivial vector space (0) when E is finite-dimensional and when n > dim(E). This chapter provides the firm foundations for understanding differential forms.
 粗略地说，我们现在处于行列式的世界，而不是永久性的世界。然而，也有一些基本的区别，其中一个是，当e为有限维和n>dim（e）时，外张量幂Vn（e）是平凡向量空间（0）。本章为理解微分形式提供了坚实的基础。

As in the case of symmetric tensor powers, since we already have the tensor algebra T(V ), we can proceed rather quickly. But first let us review some basic definitions and facts.
 在对称张量幂的情况下，由于我们已经有了张量代数t（v），我们可以很快地进行。但首先让我们回顾一些基本的定义和事实。

Definition 33.1. Let f : En → F be a multilinear map. We say that f alternating iff for all ui ∈ E, f(u1,...,un) = 0 whenever ui = ui+1, for some i with 1 ≤ i ≤ n − 1; that is, f(u1,...,un) = 0 whenever two adjacent arguments are identical. We say that f is skew-symmetric (or anti-symmetric) iff
 定义33.1.设f:en→f为多行地图。我们说，当ui=ui+1时，f（u1，…，un）=0，对于某些i，当1≤i≤n-1时，f（u1，…，un）=0，即当两个相邻参数相同时，f（u1，…，un）=0。我们说f是斜对称（或反对称）iff

f(uσ(1),...,uσ(n)) = sgn(σ)f(u1,...,un),
 f（uσ（1），…，uσ（n））=sgn（σ）f（u1，…，un）

for every permutation σ ∈ Sn, and all ui ∈ E.
 对于每一个置换，σ∈sn，和所有ui∈e。

For n = 1, we agree that every linear map f : E → F is alternating. The vector space of all multilinear alternating maps f : En → F is denoted Altn(E;F). Note that Alt1(E;F) = Hom(E,F). The following basic proposition shows the relationship between alternation and skew-symmetry.
 对于n=1，我们同意每个线性映射f:e→f是交替的。所有多行交替映射f:en→f的向量空间表示为altn（e；f）。注意alt1（e；f）=hom（e，f）。下面的基本命题说明了交替对称与斜对称的关系。

1099
 一千零九十九

Proposition 33.1. Let f : En → F be a multilinear map. If f is alternating, then the following properties hold:
 提案33.1.设f:en→f为多行地图。如果f是交替的，则以下属性保持不变：

*(1)*     For all i, with 1 ≤ i ≤ n − 1,
 对于所有i，1≤i≤n-1，

f(...,ui,ui+1,...) = −f(...,ui+1,ui,...).
 f（…，ui，ui+1，…）=-f（…，ui+1，ui，…）。

*(2)*     For every permutation σ ∈ Sn,
 对于每一个置换σ∈sn，

f(uσ(1),...,uσ(n)) = sgn(σ)f(u1,...,un).
 f（uσ（1），…，uσ（n））=sgn（σ）f（u1，…，un）。

*(3)*     For all i,j, with 1 ≤ i < j ≤ n,
 对于所有i，j，1≤i<j≤n，

​                                                    f(...,ui,...uj,...) = 0           whenever ui = uj.
 当ui=uj时，f（…，ui，…uj，…）=0。

Moreover, if our field K has characteristic different from 2, then every skew-symmetric multilinear map is alternating.
 此外，如果我们的场k的特征不同于2，那么每个斜对称多行映射都是交替的。

Proof. (1) By multilinearity applied twice, we have
 证据。（1）通过应用两次多语种，我们已经

f(...,ui + ui+1,ui + ui+1,...) = f(...,ui,ui,...) + f(...,ui,ui+1,...)
 f（…，ui+ui+1，ui+ui+1，…）=f（…，ui，ui，…）+f（…，ui，ui+1，…）

\+ f(...,ui+1,ui,...) + f(...,ui+1,ui+1,...).
 +f（…，ui+1，ui，…）+f（…，ui+1，ui+1，…）。

Since f is alternating, we get
 因为f是交替的，我们得到

0 = f(...,ui,ui+1,...) + f(...,ui+1,ui,...);
 0=f（…，ui，ui+1，…）+f（…，ui+1，ui，…）；

that is, f(...,ui,ui+1,...) = −f(...,ui+1,ui,...).
 也就是说，f（…，ui，ui+1，…）=f（…，ui+1，ui，…）。

(2)              Clearly, the symmetric group, Sn, acts on Altn(E;F) on the left, via
 显然，对称群sn作用于左边的altn（e；f），via

σ · f(u1,...,un) = f(uσ(1),...,uσ(n)).
 σ·f（u1，…，u n）=f（uσ（1），…，uσ（n））。

Consequently, as Sn is generated by the transpositions (permutations that swap exactly two elements), since for a transposition, (2) is simply (1), we deduce (2) by induction on the number of transpositions in σ.
 因此，由于sn是由换位（正好交换两个元素的换位）生成的，因为对于换位，（2）是简单的（1），我们通过诱导σ中换位的数量来推导（2）。

(3)              There is a permutation σ that sends ui and uj respectively to u1 and u2. By hypothesis ui = uj, so we have uσ(1) = uσ(2), and as f is alternating we have
 有一个排列σ，它将ui和uj分别发送到u1和u2。假设ui=uj，那么我们有uσ（1）=uσ（2），当f是交替的，我们有

f(uσ(1),...,uσ(n)) = 0.
 f（uσ（1），…，uσ（n））=0.

However, by (2),
 然而，在（2）中，

f(u1,...,un) = sgn(σ)f(uσ(1),...,uσ(n)) = 0.
 f（u1，…，u n）=sgn（σ）f（uσ（1），…，uσ（n））=0。

Now when f is skew-symmetric, if σ is the transposition swapping ui and ui+1 = ui, as sgn(σ) = −1, we get
 当f为斜对称时，如果σ为换位交换ui且ui+1=ui，当sgn（σ）=1时，我们得到

f(...,ui,ui,...) = −f(...,ui,ui,...),
 f（…，ui，ui，…）=-f（…，ui，ui，…），


 

33.1. EXTERIOR TENSOR POWERS
 33.1。外张量幂

so that
 以便

2f(...,ui,ui,...) = 0,
 2f（…，ui，ui，…）=0，

and in every characteristic except 2, we conclude that f(...,ui,ui,...) = 0, namely f is alternating.     
 在除2之外的所有特征中，我们得出f（…，ui，ui，…）=0，即f是交替的。

Proposition 33.1 shows that in every characteristic except 2, alternating and skewsymmetric multilinear maps are identical. Using Proposition 33.1 we easily deduce the following crucial fact.
 命题33.1表明，除2外，在每个特征中，交替和偏对称多行映射是相同的。利用33.1号提案，我们很容易推断出以下关键事实。

Proposition 33.2. Let f : En → F be an alternating multilinear map. For any families of vectors, (u1,...,un) and (v1,...,vn), with ui,vi ∈ E, if
 提案33.2.设f:en→f为交替多行地图。对于任何向量族，（u1，…，un）和（v1，…，vn），带有ui，vi∈e，if

​                                                                ,                       1 ≤ j ≤ n,
 ，1≤j≤n，

then
 然后

,
 ，

where A is the n × n matrix, A = (aij).
 其中a是n×n矩阵，a=（aij）。

Proof. Use Property (ii) of Proposition 33.1.                                                                                  
 证据。使用提案33.1的财产（ii）。

We are now ready to define and construct exterior tensor powers.
 我们现在已经准备好定义和构造外部张量幂。

Definition 33.2. An n-th exterior tensor power of a vector space E, where n ≥ 1, is a vector space A together with an alternating multilinear map ϕ: En → A, such that for every vector space F and for every alternating multilinear map f : En → F, there is a unique linear map f∧ : A → F with
 定义33.2.向量空间e的第n次外张量幂，其中n≥1，是向量空间a加上交替的多行映射，使得对于每个向量空间f和每个交替的多行映射f:en→f，都有一个唯一的线性映射f：a→f，其中

f(u1,...,un) = f∧(ϕ(u1,...,un)),
 f（u1，…，un）=f（（u1，…，un）），

for all u1,...,un ∈ E, or for short
 对于所有的u1，…，un∈e，或简称

f = f∧ ◦ ϕ.
 F=F _。

Equivalently, there is a unique linear map f∧ such that the following diagram commutes:
 同样地，有一个独特的线性图f，这样下图就可以通勤：

EnDDDDϕDDDD!/ A f∧
 endddd_dddd！/A F_

f
 f

F.
 f.

The above property is called the universal mapping property of the exterior tensor power (A,ϕ).
 上述性质称为外张量幂（A，_）的普适映射性质。

We now show that any two n-th exterior tensor powers (A1,ϕ1) and (A2,ϕ2) for E are isomorphic.
 我们现在证明，e的任意两个n次外部张量幂（a1，_）和（a2，_）是同构的。

Proposition 33.3. Given any two n-th exterior tensor powers (A1,ϕ1) and (A2,ϕ2) for E, there is an isomorphism h: A1 → A2 such that
 提案33.3.考虑到e的任意两个n阶外张量幂（a1，_）和（a2，_），存在同构h:a1→a2，这样

ϕ2 = h ◦ ϕ1.
 _2=H_1.

Proof. Replace tensor product by n-th exterior tensor power in the proof of Proposition
 证据。在命题证明中用第n次外张量幂代替张量积

32.5.                                                                                                                                                    
 32.5。

We next give a construction that produces an n-th exterior tensor power of a vector space E.
 接下来我们给出一个构造，它产生向量空间e的第n次外张量幂。

Theorem 33.4. Given a vector space E, an n-th exterior tensor power (Vn(E),ϕ) for E can be constructed (n ≥ 1). Furthermore, denoting ϕ(u1,...,un) as u1 ∧···∧un, the exterior tensor power Vn(E) is generated by the vectors u1 ∧ ··· ∧ un, where u1,...,un ∈ E, and for every alternating multilinear map f : En → F, the unique linear map f∧ : Vn(E) → F such that f = f∧ ◦ ϕ is defined by
 定理33.4。给定向量空间e，可构造e的第n次外张量幂（vn（e），a）（n≥1）。此外，将_（u1，…，un）表示为u1····un，外部张量幂Vn（e）由矢量u1··············un生成，其中u1，…，un∈e，对于每个交替的多线性映射f:en→f，唯一的线性映射f：vn（e）→f，这样f=f

f∧(u1 ∧ ··· ∧ un) = f(u1,...,un)
 f（u1····un）=f（u1，…，un）

on the generators u1 ∧ ··· ∧ un of Vn(E).
 在VN（E）的U1····Un发电机上。

Proof sketch. We can give a quick proof using the tensor algebra T(E). Let Ia be the two-sided ideal of T(E) generated by all tensors of the form u ⊗ u ∈ E⊗2. Then let
 证明草图。我们可以用张量代数t（e）给出一个快速的证明。假设Ia是由u u∈e 2形式的所有张量产生的t（e）的双面理想。那就让

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image002.gif)

and let π be the projection π: E⊗n → Vn(E). If we let u1 ∧ ··· ∧ un = π(u1 ⊗ ··· ⊗ un), it is easy to check that (Vn(E),∧) satisfies the conditions of Theorem 33.4. 
 设π为投影π：e n→vn（e）。如果我们让u1·····un=π（u1·····un），很容易检查（vn（e），）满足定理33.4的条件。

Remark: We can also define
 备注：我们也可以定义

,
 ，

the exterior algebra of E. This is the skew-symmetric counterpart of S(E), and we will study it a little later.
 E的外代数，这是S（E）的斜对称对应物，稍后我们将研究它。

For simplicity of notation, we may write Vn E for Vn(E). We also abbreviate “exterior tensor power” as “exterior power.” Clearly, V1(E) ∼= E, and it is convenient to set V0(E) = K.
 为了便于记法，我们可以为vn（e）写vn e。我们还将“外张量幂”缩写为“外张量幂”。显然，v1（e）=e，并且设置v0（e）=k很方便。

33.1. EXTERIOR TENSOR POWERS
 33.1。外张量幂

The fact that the map ϕ: En → Vn(E) is alternating and multilinear can also be expressed as follows:
 图_：en→vn（e）是交替的，多行也可以表示为：

| u1 ∧ ··· ∧ (ui + vi) ∧ ···   ∧ un    U1·····（UI+VI）·········UN | =    = | (u1 ∧ ··· ∧ ui ∧ ··· ∧ un)    （U1·········Ui····Un）   + (u1 ∧ ··· ∧ vi ∧ ··· ∧ un),    +（U1··············联合国） |
| ------------------------------------------------------------ | ------ | ------------------------------------------------------------ |
| u1 ∧ ··· ∧ (λui) ∧ ··· ∧   un    U1···（λui）····un          | =    = | λ(u1 ∧ ···   ∧ ui ∧ ··· ∧ un),    λ（u1·········uI···un）    |
| uσ(1) ∧ ··· ∧ uσ(n)    uσ（1）···uσ（n）   for all σ   ∈ Sn.    对于所有的σ∈sn。 | =    = | sgn(σ)u1 ∧   ··· ∧ un,    sgn（σ）u1····un，                 |

The map ϕ from En to Vn(E) is often denoted ι∧, so that
 从en到vn（e）的图_通常表示为，因此

ι∧(u1,...,un) = u1 ∧ ··· ∧ un.
 （u1，…，un）=u1···un.

Theorem 33.4 implies the following result. Proposition 33.5. There is a canonical isomorphism
 定理33.4包含以下结果。提案33.5。有一个典型的同构

n
 n

Hom(^(E),F) ∼= Altn(E;F)
 hom（^（e），f）=altn（e；f）

between the vector space of linear maps Hom(Vn(E),F) and the vector space of alternating multilinear maps Altn(E;F), given by the linear map − ◦ ϕ defined by →7 h ◦ ϕ, with h ∈ Hom(Vn(E),F). In particular, when F = K, we get a canonical isomorphism
 在线性映射的向量空间hom（vn（e），f）和交替多线性映射的向量空间altn（e；f）之间，由线性映射−_定义为→7 h _，其中h∈hom（vn（e），f）给出。特别是，当f=k时，我们得到一个正则同构。

.
 .

Definition 33.3. Tensors α ∈ Vn(E) are called alternating n-tensors or alternating tensors of degree n and we write deg(α) = n. Tensors of the form u1∧···∧un, where ui ∈ E, are called simple (or decomposable) alternating n-tensors. Those alternating n-tensors that are not simple are often called compound alternating n-tensors. Simple tensors u1∧···∧un ∈ Vn(E) are also called n-vectors and tensors in Vn(E∗) are often called (alternating) n-forms.
 定义33.3.张量α∈vn（e）称为n阶交替张量或n阶交替张量，我们写出deg（α）=n。形式为u1·····un的张量，其中ui∈e称为简单（或可分解）交替n张量。那些不简单的交替n-张量通常称为复合交替n-张量。简单张量u1·····un∈vn（e）也称为N矢量，vn（e）中的张量常称为（交替）N型。

Given two linear maps f : E → E0 and g: E → E0, since the map) is bilinear and alternating, there is a unique linear map f ∧ g: V2(E) → V2(E0) making the following diagram commute:
 给定两个线性映射f:e→e0和g:e→e0，由于映射）是双线性且交替的，因此有一个唯一的线性映射f g:v2（e）→v2（e0），使以下图表成为通勤图：

​                                                                 E2     ι∧    / V2(E)
 e2/v2（e）

f×gf∧g
 f×gf g

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image003.gif)

​                                                               (E )       0 /      (E0).
 （e）0/（e0）。

ι∧
 γ射线

The map f ∧ g: V2(E) → V2(E0) is determined by
 图f g:v2（e）→v2（e0）由

(f ∧ g)(u ∧ v) = f(u) ∧ g(u).
 （f_g）（u_v）=f（u）g（u）。

Proposition 33.6. Given any linear maps f : E → E0, g: E → E0, f0 : E0 → E00 and g0 : E0 → E00, we have
 提案33.6.对于任何线性映射f:e→e0，g:e→e0，f0:e0→e00和g0:e0→e00，我们有

(f0 ◦ f) ∧ (g0 ◦ g) = (f0 ∧ g0) ◦ (f ∧ g).
 （f0 f）（g0 g）=（f0 g0）（f g）。

The generalization to the alternating product f1∧···∧fn of n ≥ 3 linear maps fi : E → E0 is immediate, and left to the reader.
 n≥3个线性映射fi:e→e0的交替积f1······fn的推广是直接的，留给读者。

## 33.2        Bases of Exterior Powers  33.2外部权力基础

Definition 33.4. Let E be any vector space. For any basis (ui)i∈Σ for E, we assume that some total ordering ≤ on the index set Σ has been chosen. Call the pair ((ui)i∈Σ,≤) an ordered basis. Then for any nonempty finite subset I ⊆ Σ, let
 定义33.4.设e为任意向量空间。对于任意基（ui）i∈∑对于e，我们假设在索引集∑上选择了一些总序。称对（（ui）i∈∑，≤）为有序基。那么对于任何非空有限子集i∑，让

uI = ui1 ∧ ··· ∧ uim,
 ui=ui1···uim，

where I = {i1,...,im}, with i1 < ··· < im.
 式中，i=i1，…，im，其中i1<······<im.

Since Vn(E) is generated by the tensors of the form v1 ∧···∧vn, with vi ∈ E, in view of skew-symmetry, it is clear that the tensors uI with |I| = n generate Vn(E) (where ((ui)i∈Σ,≤) is an ordered basis). Actually they form a basis. To gain an intuitive understanding of this statement, let m = 2 and E be a 3-dimensional vector space lexicographically ordered basis {e1,e2,e3}. We claim that
 由于vn（e）是由v1····vn形式的张量生成的，因此，从斜对称性的角度来看，i=n形式的张量ui生成vn（e）（其中（（ui）i∈∑，≤）是有序基）。实际上，它们构成了一个基础。为了直观地理解这句话，让m=2和e是一个三维向量空间，在词典上是有序的基e1，e2，e3。我们声称

​                                                   e1 ∧ e2,        e1 ∧ e3,       e2 ∧ e3
 e1 e2、e1 e3、e2 e3

form a basis for V2(E) since they not only generate V2(E) but are linearly independent. The linear independence is argued as follows: given any vector space F, if w12,w13,w23 are any vectors in F, there is an alternating bilinear map h: E2 → F such that
 形成V2（e）的基础，因为它们不仅生成V2（e），而且是线性独立的。线性独立性的论证如下：给定任意向量空间f，如果w12、w13、w23是f中的任意向量，则存在一个交替的双线性映射h:e2→f，从而

​                              h(e1,e2) = w12,        h(e1,e3) = w13,        h(e2,e3) = w23.
 h（e1，e2）=w12，h（e1，e3）=w13，h（e2，e3）=w23。

Because h yields a unique linear map h∧ : V2 E → F such that
 因为h生成一个唯一的线性映射h：v2 e→f这样

​                                                  h∧(ei ∧ ej) = wij,        1 ≤ i < j ≤ 3,
 h（ei ej）=wij，1≤i<j≤3，

by Proposition 32.4, the vectors
 根据命题32.4，向量

​                                                   e1 ∧ e2,        e1 ∧ e3,       e2 ∧ e3
 e1 e2、e1 e3、e2 e3

are linearly independent. This suggests understanding how an alternating bilinear function f : E2 → F is expressed in terms of its values f(ei,ej) on the basis vectors (e1,e2,e3). Using bilinearity and alternation, we obtain
 线性无关。这意味着要理解交替双线性函数f:e2→f是如何在基向量（e1，e2，e3）上用其值f（ei，ej）表示的。利用双线性和交替，我们得到

f(u1e1 + u2e2 + u3e3,v1e1 + v2e2 + v3e3) = (u1v2 − u2v1)f(e1,e2) + (u1v3 − u3v1)f(e1,e3) + (u2v3 − u3v2)f(e2,e3).
 f（u1e1+u2e2+u3e3，v1e1+v2e2+v3e3）=（u1v2−u2v1）f（e1，e2）+（u1v3−u3v1）f（e1，e3）+（u2v3−u3v2）f（e2，e3）。

33.2. BASES OF EXTERIOR POWERS
 33.2。外部权力基础

Therefore, given w12,w13,w23 ∈ F, the function h given by h(u1e1 + u2e2 + u3e3,v1e1 + v2e2 + v3e3) = (u1v2 − u2v1)w12 + (u1v3 − u3v1)w13
 因此，给定w12，w13，w23∈f，h给出的函数h（u1e1+u2e2+u3e3，v1e1+v2e2+v3e3）=（u1v2−u2v1）w12+（u1v3−u3v1）w13

\+ (u2v3 − u3v2)w23
 +（u2v3−u3v2）w23

is clearly bilinear and alternating, and by construction h(ei,ej) = wij, with 1 ≤ i < j ≤ 3 does the job.
 明显是双线性和交替的，并且通过构造h（ei，ej）=wij，1≤i<j≤3来完成工作。

We now prove the assertion that tensors uI with |I| = n generate Vn(E) for arbitrary n.
 我们现在证明了张量ui with i=n生成vn（e）用于任意n的断言。

Proposition 33.7. Given any vector space E, if E has finite dimension d = dim(E), then for all n > d, the exterior power Vn(E) is trivial; that is Vn(E) = (0). If n ≤ d or if E is infinite dimensional, then for every ordered basisVn(E), where I ranges over finite nonempty subsets of((uΣi)i∈of sizeΣ,≤), the family|I| = n. (uI) is basis of
 提案33.7。对于任何向量空间e，如果e的有限维d=dim（e），那么对于所有n>d，外幂Vn（e）都是微不足道的；即Vn（e）=0。如果n≤d或者e是无限维，那么对于每一个有序的basisvn（e），其中i的范围在（（u∑i）i∈的有限非空子集上，≤），族i=n（ui）是

Proof. First assume that E has finite dimension d = dim(E) and that n > d. We know that Vn(E) is generated by the tensors of the form v1 ∧ ··· ∧ vn, with vi ∈ E. If u1,...,ud is a basis of E, as every vi is a linear combination of the uj, when we expand v1 ∧ ··· ∧ vn using multilinearity, we get a linear combination of the form
 证据。首先假设e有有限维d=dim（e）和n>d，我们知道vn（e）是由形式v1·····vn的张量生成的，其中vi∈e。如果u1，…，ud是e的基础，因为当我们使用多线性展开v1······vn时，每个vi都是uj的线性组合，我们得到了形式的线性组合

v1 ∧ ··· ∧ vn = X λ(j1,...,jn) uj1 ∧ ··· ∧ ujn,
 v1···vn=xλ（j1，…，jn）uj1···ujn，

(j1,...,jn)
 （j1，…，jn）

where each (j1,...,jn) is some sequence of integers jk ∈ {1,...,d}. As n > d, each sequence (j1,...,jn) must contain two identical elements. By alternation, uj1 ∧ ··· ∧ ujn = 0, and so v1 ∧ ··· ∧ vn = 0. It follows that Vn(E) = (0).
 其中，每个（j1，…，jn）是一些整数序列jk∈1，…，d。由于n>d，每个序列（j1，…，jn）必须包含两个相同的元素。通过交替，uj1····ujn=0，因此v1···vn=0。由此得出Vn（e）=（0）。

Now assume that either dim(E) = d and n ≤ d, or that E is infinite dimensional. The argument below shows that the uI are nonzero and linearly independent. As usual, let  be the linear form given by
 现在假设dim（e）=d和n≤d，或者e是无限维。下面的参数显示用户界面是非零的，并且是线性独立的。和往常一样，假设线性形式由

.
 .

For any nonempty subset I = {i1,...,in} ⊆ Σ with i1 < ··· < in, for any n vectors v1,...,vn ∈ E, let
 对于任何非空子集i=i1，…，i n∑with i1<····<in，对于任意n向量v1，…，vn∈e，let

.
 .

If we let the n-tuple (v1,...,vn) vary we obtain a map lI from En to K, and it is easy to check that this map is alternating multilinear. Thus lI induces a unique linear map LI : Vn(E) → K making the following diagram commute.
 如果让n元组（v1，…，vn）发生变化，我们得到一个从en到k的映射li，并且很容易检查该映射是否是交替多行的。因此，li归纳出一个独特的线性图li:vn（e）→k，使下面的图表通勤。

EnHHHιlH∧IHHH/HHVH$ n( LEI )
 ehh lh ihh/hhvh$N（LEI）

K
 K

Observe that for any nonempty finite subset J ⊆ Σ with |J| = n, we have
 注意，对于任何非空有限子集j∑，j=n，我们有

.
 .

Note that when dim(E) = d and n ≤ d, or when E is infinite-dimensional, the forms  are all distinct, so the above does hold. Since LI(uI) = 1, we conclude that
 请注意，当dim（e）=d和n≤d时，或者当e是无限维时，这些形式都是不同的，因此上面的内容是成立的。由于li（ui）=1，我们得出结论：

uI = 06 . If we have a linear combination
 ui=06。如果我们有一个线性组合

,
 ，

where the above sum is finite and involves nonempty finite subset I ⊆ Σ with |I| = n, for every such I, when we apply LI we get λI = 0, proving linear independence. 
 当上面的和是有限的并且涉及非空的有限子集i∑with i=n时，对于每一个这样的i，当我们应用li时，我们得到λi=0，证明线性独立性。

As a corollary, if E is finite dimensional, say dim(E) = d, and if 1 ≤ n ≤ d, then we have
 作为推论，如果e是有限维的，比如dim（e）=d，如果1≤n≤d，那么我们有

dim(,
 昏暗的

and if n > d, then dim(Vn(E)) = 0.
 如果n>d，则dim（vn（e））=0。

Remark: When n = 0, if we set u∅ = 1, then (u∅) = (1) is a basis of V0(V ) = K.
 注：当n=0时，如果设u∅=1，则（u∅）=（1）为v0（v）=k的基础。

It follows from Proposition 33.7 that the family (uI)I where I ⊆ Σ ranges over finite subsets of Σ is a basis of V(V ) = Ln≥0 Vn(V ).
 由命题33.7得出，i∑在∑的有限子集上的族（ui）i是v（v）=ln≥0 vn（v）的基础。

As a corollary of Proposition 33.7 we obtain the following useful criterion for linear independence.
 作为33.7号命题的推论，我们得到了以下关于线性独立性的有用准则。

Proposition 33.8. For any vector space E, the vectors u1,...,un ∈ E are linearly independent iff u1 ∧ ··· ∧ un = 06 .
 提案33.8。对于任意向量空间e，向量u1，…，un∈e是线性无关的iff u1···un=06。

Proof. If u1 ∧ ··· ∧ un = 06 , then u1,...,un must be linearly independent. Otherwise, some ui would be a linear combination of the other uj’s (with j =6 i), and then, as in the proof of Proposition 33.7, u1 ∧···∧un would be a linear combination of wedges in which two vectors are identical, and thus zero.
 证据。如果U1····un=06，那么U1，…，un必须是线性无关的。否则，一些ui将是另一个uj的线性组合（j=6i），然后，如在命题33.7的证明中，u1······un将是两个向量相同，因而为零的楔形的线性组合。

Conversely, assume that u1,...,un are linearly independent. Then we have the linear forms such that
 相反，假设u1，…，un是线性无关的。那么我们有这样的线性形式

​                                                                                    1 ≤ i,j ≤ n.
 1≤i，j≤n。

As in the proof of Proposition 33.7, we have a linear map Lu1,...,un : Vn(E) → K given by
 如在33.7号命题的证明中，我们有一个线性图lu1，…，un:vn（e）→k，由

,
 ，

for all v1 ∧···∧vn ∈ Vn(E). As Lu1,...,un(u1 ∧···∧un) = 1, we conclude that u1 ∧···∧un 6=
 对于所有v1····vn∈vn（e）。作为lu1，…，un（u1·····un）=1，我们得出u1·····un 6=

\0.                                                                                                                                                         
 0。

33.3. SOME USEFUL ISOMORPHISMS FOR EXTERIOR POWERS
 小精灵。关于外部力量的一些有用同构

Proposition 33.8 shows that geometrically every nonzero wedge u1 ∧ ··· ∧ un corresponds to some oriented version of an n-dimensional subspace of E.
 命题33.8表明，几何上每一个非零楔形U1····Un对应于E的N维子空间的一些定向版本。

## 33.3          Some Useful Isomorphisms for Exterior Powers  33.3外部力量的一些有用同构

We can show the following property of the exterior tensor product, using the proof technique of Proposition 32.13.
 利用32.13命题的证明技术，我们可以证明外张量积的以下性质。

Proposition 33.9. We have the following isomorphism:
 提案33.9.我们有以下同构：

​                                                 ^n                    Mn ^k          n^−k
 ^ N mn^k N^−k

​                                                     (E ⊕ F) ∼=            (E) ⊗       (F).
 （e_f）=（e）（f）。

k=0
 K＝0

## 33.4        Duality for Exterior Powers  33.4外部权力的双重性

In this section all vector spaces are assumed to have finite dimension. We define a nondegenerate pairing Vn(E∗) × Vn(E) −→ K as follows: Consider the multilinear map
 在本节中，假设所有向量空间都有有限维。我们定义了一个非退化配对vn（e）×vn（e）−→k如下：考虑多行映射

(E∗)n × En −→ K
 （e）n×en−→k

given by
 给出者

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image005.gif)

It is easily checked that this expression is alternating w.r.t. the ui’s and also w.r.t. the.
 很容易检查该表达式是否交替使用了UI和W.R.T.。

For any fixed (, we get an alternating multilinear map
 对于任何固定的（，我们得到一个交替的多行映射

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image007.gif)

from En to K. The map extends uniquely to a linear map making the following diagram commute:
 从en到k。地图独特地延伸到线性地图，使以下图表通勤：

EnHHHιH∧HHHH/ HVH$ n( E)
 n h h_h_hhh/hvh$N（E）

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image009.gif)

K.
 K

We also have the alternating multilinear map
 我们还有交替的多行地图

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image011.gif)

from (E∗)n to Hom(Vn(E),K), which extends to a linear map L from Vn(E∗) to Hom(Vn(E),K) making the following diagram commute:
 从（e）n到hom（vn（e），k），它延伸到从vn（e）到hom（vn（e），k的线性图l，使以下图表通勤：

​                                                     (E∗)n      ι∧∗      / Vn(E∗)
 （E）N/VN（E）

 L
 L

' Vn (E),K). Hom(
 ‘VN（e），k）。霍姆

However, in view of the isomorphism
 然而，鉴于同构

Hom(U ⊗ V,W) ∼= Hom(U,Hom(V,W)),
 hom（u v，w）=hom（u，hom（v，w）），

with U = Vn(E∗), V = Vn(E) and W = K, we can view L as a linear map
 当u=vn（e）、v=vn（e）和w=k时，我们可以将l视为线性映射。

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image013.gif)

which by Proposition 32.8 corresponds to a bilinear map
 根据命题32.8，它对应于双线性图。

​                                                                                                                                                       (∗)
 （三）

This pairing is given explicitly in terms of generators by
 这种配对是根据发电机明确给出的

.
 .

Now this pairing in nondegenerate. This can be shown using bases. Given any basis (e1,...,em) of E, for every basis element ) (with 1 ≤ i1 < ··· < in ≤ m), we have
 现在这个配对是非退化的。这可以用碱来表示。给定e的任何基（e1，…，e m），对于每个基元（1≤i1<·······<in≤m），我们有

(
 （

he∗i1 ∧ ··· ∧ e∗in,ej1,...,ejni =      1,...,jn) = (i1,...,in) 1 if (j
 He i1·····e in，e j 1，…，ejni=1，…，jn）=（i1，…，in）1如果（j

​                                                                               0   otherwise.
 否则为0。

We leave the details as an exercise to the reader. As a consequence we get the following canonical isomorphisms.
 我们把细节留给读者作为练习。因此，我们得到了以下规范同构。

Proposition 33.10. There is a canonical isomorphism
 提案33.10。有一个典型的同构

.
 .

There is also a canonical isomorphism
 还有一个典型的同构

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image015.gif)

which allows us to interpret alternating tensors over E∗ as alternating multilinear maps.
 这使得我们可以把E上的交替张量解释为交替的多行映射。

33.4. DUALITY FOR EXTERIOR POWERS
 33.4。外部力量的二重性

Proof. The second isomorphism follows from the canonical isomorphism (Vn(E))∗ ∼= Vn(E∗) and the canonical isomorphism (Vn(E))∗ ∼= Altn(E;K) given by Proposition 33.5. 
 证据。第二个同构来自33.5号命题给出的规范同构（vn（e））～=vn（e）和规范同构（vn（e））～=altn（e；k）。

Remarks:
 评论：

\1.    The isomorphism µ: Vn(E∗) ∼= Altn(E;K) discussed above can be described explicitly as the linear extension of the map given by
 上述讨论的同构（e））=altn（e；k）可以明确地描述为图的线性延伸

.
 .

\2.    The canonical isomorphism of Proposition 33.10 holds under more general conditions. Namely, that K is a commutative ring with identity and that E is a finitely-generated projective K-module (see Definition 34.7). See Bourbaki, [25] (Chapter III, §11, Section 5, Proposition 7).
 33.10命题的规范同构在更一般的条件下成立。也就是说，k是一个具有恒等式的交换环，e是一个有限生成的射影k模（见定义34.7）。见Bourbaki，[25]（第三章，第11节，第5节，提案7）。

\3.    Variants of our isomorphism µ are found in the literature. For example, there is a version µ0, where
 文献中发现了我们的同构μ的变体。例如，有一个版本祄0，其中

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image017.gif)

with the factor  added in front of the determinant. Each version has its its own merits and inconveniences. Morita [125] uses µ0 because it is more convenient than µ when dealing with characteristic classes. On the other hand, µ0 may not be defined for a field with positive characteristic, and when using µ0, some extra factor is needed in defining the wedge operation of alternating multilinear forms (see Section 33.5) and for exterior differentiation. The version µ is the one adopted by Warner [180], Knapp [102], Fulton and Harris [69], and Cartan [34, 35].
 在行列式前面加上因子。每个版本都有自己的优点和不便。森田[125]使用了μ0，因为它在处理特征类时比μ更方便。另一方面，对于具有正特性的场，可以不定义μ0，当使用μ0时，在定义交替多行形式的楔形操作（见第33.5节）和外部差异时，需要一些额外的因素。版本μ是华纳[180]、纳普[102]、富尔顿和哈里斯[69]以及卡坦[34，35]采用的版本。

If f : E → F is any linear map, by transposition we get a linear map f> : F ∗ → E∗ given by
 如果f:e→f是任何线性映射，通过换位我们得到一个线性映射f>：f→e，由

​                                                      f>(v∗) = v∗ ◦ f,         v∗ ∈ F ∗.
 f>（v）=v f，v∈f。

Consequently, we have
 因此，我们

​                                f>(v∗)(u) = v∗(f(u)),           for all u ∈ E and all v∗ ∈ F ∗.
 f>（v）（u）=v（f（u）），对于所有u e和所有v∈f。

For any p ≥ 1, the map
 对于任何p≥1，图

(u1,...,up) 7→ f(u1) ∧ ··· ∧ f(up)
 （U1，…，向上）7→F（U1）···F（向上）

from Ep to Vp F is multilinear alternating, so it induces a unique linear map Vp f : Vp E → Vp F making the following diagram commute
 从ep到vp f是多行交替的，因此它会产生一个独特的线性映射vp f:vp e→vp f，从而使下图变为通勤图。

​                                                                 Ep    ι∧  / Vp E
 ep/vp e

​                                                                 EEEEEEEEEV"  p VF,p f
 eeeeeeeee v“p v f，p f

and defined on generators by
 在发电机上定义

.
 .

Combining Vp and duality, we get a linear map Vp f> : Vp F ∗ → Vp E∗ defined on generators by
 结合vp和对偶性，我们得到一个线性映射vp f>：vp f→vp e定义在生成器上

.
 .

Proposition 33.11. If f : E → F is any linear map between two finite-dimensional vector spaces E and F, then
 提案33.11.如果f:e→f是有限维向量空间e和f之间的任何线性映射，则

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image019.gif)

Proof. It is enough to prove the formula on generators. By definition of µ, we have
 证据。在发电机上证明这个公式已经足够了。根据μ的定义，我们有

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image021.gif)

as claimed.                                                                                                                                         
 如要求。

Remark: The map Vp f> is often denoted f∗, although this is an ambiguous notation since p is dropped. Proposition 33.11 gives us the behavior of Vp f> under the identification of Vp E∗ and Altp(E;K) via the isomorphism µ.
 备注：map vp f>通常表示为f，尽管这是一个不明确的符号，因为p被删除了。命题33.11通过同构μ给出了vp e和altp（e；k）标识下vp f>的行为。

As in the case of symmetric powers, the map from En to Vn(E) given by (u,...,un) 7→ u1 ∧···∧ un yields a surjection π: E⊗n → Vn(E). Now this map has some section, so there is some injection η: Vn(E) → E⊗n with π ◦ η = id. As we saw in Proposition 33.10 there is a canonical isomorphism
 在对称幂的情况下，由（u，…，u n）7→u1·······un给出的从en到vn（e）的映射产生一个投影π：e n→vn（e）。现在这个图有一个部分，所以有一些注入η：vn（e）→e n，πη=id。正如我们在命题33.10中看到的，有一个规范的同构。

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image023.gif)

for any field K, even of positive characteristic. However, if our field K has characteristic 0, then there is a special section having a natural definition involving an antisymmetrization process.
 对于任何场k，即使是正特性。然而，如果我们的场k具有0的特征，那么有一个特殊的部分具有涉及反对称化过程的自然定义。

Recall, from Section 32.10 that we have a left action of the symmetric group Sn on E⊗n.
 回想一下，在第32.10节中，对称群sn在e n上有一个左作用。

The tensors z ∈ E⊗n such that
 张量z∈e n使得

​                                                  σ · z = sgn(σ)z,      for all     σ ∈ Sn
 σ·z=sgn（σ）z，所有σ∈sn

are called antisymmetrized tensors. We define the map η: En → E⊗n by
 称为反对称张量。我们定义了图η：e n→e n

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image025.gif)

33.5. EXTERIOR ALGEBRAS
 33.5。外部代数

As the right hand side is an alternating map, we get a unique linear map Vn η: Vn(E) → E⊗n making the following diagram commute.
 由于右手边是一个交替的地图，我们得到一个独特的线性地图vnη：vn（e）→e n，使下面的图表通勤。

EnHHHιηH∧HHH/HHV# n( VEn)η
 Enhh_ηh_hh/hhv_n（ven）η

E⊗n.
 埃恩

Clearly, Vn η(Vn(E)) is the set of antisymmetrized tensors in E⊗n. If we consider the map A = (Vn η) ◦ π: E⊗n −→ E⊗n, it is easy to check that A ◦ A = A. Therefore, A is a
 显然，vnη（vn（e））是e n中反对称张量的集合。如果我们考虑映射a=（vnη）π：e n−→e n，很容易检查a a=a。因此，a是

projection, and by linear algebra, we know that
 投影，通过线性代数，我们知道

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image027.gif)

It turns out that KerA = E⊗n ∩ Ia = Ker π, where Ia is the two-sided ideal of T(E) generated by all tensors of the form u ⊗ u ∈ E⊗2 (for example, see Knapp [102], Appendix A). Therefore, Vn η is injective,
 结果表明，ker a=e n ia=kerπ，其中ia是由u u∈e 2形式的所有张量产生的t（e）的双面理想（例如，见Knapp[102]，附录A）。因此，vnη是内射的，

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image029.gif)

and the exterior tensor power Vn(E) is naturally embedded into E⊗n.
 外张量功率Vn（e）自然嵌入E n中。

## 33.5       Exterior Algebras  33.5外部代数

As in the case of symmetric tensors, we can pack together all the exterior powers Vn(V ) into an algebra.
 在对称张量的情况下，我们可以把所有的外幂vn（v）组合成一个代数。

Definition 33.5. Gieven any vector space V , the vector space
 定义33.5.即使任何向量空间v，向量空间

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image031.gif)

is called the exterior algebra (or Grassmann algebra) of V .
 称为V的外部代数（或格拉斯曼代数）。

To make V(V ) into an algebra, we mimic the procedure used for symmetric powers. If Ia is the two-sided ideal generated by all tensors of the form u ⊗ u ∈ V ⊗2, we set
 为了使V（V）变成代数，我们模拟了对称幂的过程。如果ia是由u u∈v 2形式的所有张量产生的双面理想，我们将

.
 .

Then V•(V ) automatically inherits a multiplication operation, called wedge product, and since T(V ) is graded, that is
 然后v•（v）自动继承一个称为楔形积的乘法运算，因为t（v）是分级的，也就是说

T(V ) = M V ⊗m,
 t（v）=m v m，

m≥0
 m 0

we have
 我们有

.
 .

However, it is easy to check that
 但是，很容易检查

,
 ，

so
 所以

.
 .

When V has finite dimension d, we actually have a finite direct sum (coproduct)
 当v有有限维d时，我们实际上有一个有限直和（副积）

,
 ，

and since each Vm(V ) has dimension , we deduce that
 因为每个vm（v）都有维，我们推断

dim(^(V )) = 2d = 2dim(V ).
 尺寸（^（V））=2d=2dim（V）。

The multiplication, ∧: Vm(V )×Vn(V ) → Vm+n(V ), is skew-symmetric in the following precise sense:
 乘法，：vm（v）×v n（v）→vm+n（v），在以下精确意义上是斜对称的：

Proposition 33.12. For all α ∈ Vm(V ) and all β ∈ Vn(V ), we have
 提案33.12。对于所有α∈vm（v）和所有β∈vn（v），我们有

β ∧ α = (−1)mnα ∧ β.
 βα=（-1）mNαβ。

Proof. Since v ∧ u = −u ∧ v for all u,v ∈ V , Proposition 33.12 follows by induction.                   
 证据。既然v u=−u v对于所有u，v v，命题33.12随后是归纳法。

Since α ∧ α = 0 for every simple (also called decomposable) tensor α = u1 ∧ ··· ∧ un, it seems natural to infer that α ∧ α = 0 for every tensor α ∈ V(V ). If we consider the case where dim(V ) ≤ 3, we can indeed prove the above assertion. However, if dim(V ) ≥ 4, the above fact is generally false! For example, when dim(V ) = 4, if (u1,u2,u3,u4) is a basis for V , for α = u1 ∧ u2 + u3 ∧ u4, we check that
 由于αα=0表示每个简单张量α=u1······un，因此很自然地推断αα=0表示每个张量α∈v（v）。如果我们考虑dim（v）≤3的情况，我们确实可以证明上述观点。然而，如果dim（v）≥4，上述事实通常是错误的！例如，当dim（v）=4时，如果（u1，u2，u3，u4）是v的基础，对于α=u1 u2+u3 u4，我们检查

α ∧ α = 2u1 ∧ u2 ∧ u3 ∧ u4,
 αα=2u1 u2 u3 u4，

which is nonzero. However, if α ∈ Vm E with m odd, since m2 is also odd, we have
 这不是零。然而，如果α∈vm e与m奇数，由于m2也是奇数，我们有

α ∧ α = (−1)m2α ∧ α = −α ∧ α,
 αα=−1）m2αα=−αα，

so indeed α ∧ α = 0 (if K is not a field of characteristic 2).
 因此，实际上αα=0（如果k不是特征2的场）。

33.5. EXTERIOR ALGEBRAS
 33.5。外部代数

The above discussion suggests that it might be useful to know when an alternating tensor is simple (decomposable). We will show in Section 33.7 that for tensors α ∈ V2(V ), α∧α = 0 iff α is simple.
 上述讨论表明，知道交变张量何时是简单的（可分解的）可能是有用的。我们将在第33.7节中说明，对于张量α∈v2（v），α_α=0 iffα是简单的。

A general criterion for decomposability can be given in terms of some operations known as left hook and right hook (also called interior products); see Section 33.7.
 可分解性的一般标准可根据一些被称为左钩和右钩（也称为内部产品）的操作给出；见第33.7节。

It is easy to see that V(V ) satisfies the following universal mapping property.
 很容易看出，V（V）满足以下通用映射性质。

Proposition 33.13. Given any K-algebra A, for any linear map f : V → A, if (f(v))2 = 0
 提案33.13。给定任意k-代数a，对于任意线性映射f:v→a，如果（f（v））2=0

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image032.gif)

for all v ∈ V , then there is a unique K-algebra homomorphism f : V(V ) → A so that
 对于所有的v∈v，则有一个唯一的k-代数同态f:v（v）→a，因此

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image033.gif)

f = f ◦ i,
 f=f_i，

as in the diagram below.
 如下图所示。

V FFFfFFiFF/ FVF" (Vf )
 v ffffff/fvf”（vf）

A
 一

When E is finite-dimensional, recall the isomorphism µ: Vn(E∗) −→ Altn(E;K), defined as the linear extension of the map given by
 当e是有限维时，回想同构：vn（e）−→altn（e；k），定义为由

.
 .

Now, we have also a multiplication operation Vm(E∗) × Vn(E∗) −→ Vm+n(E∗). The following question then arises:
 现在，我们还有一个乘法运算vm（e）×vn（e）−→vm+n（e）。然后出现以下问题：

Can we define a multiplication Altm(E;K) × Altn(E;K) −→ Altm+n(E;K) directly on alternating multilinear forms, so that the following diagram commutes?
 我们能在交替的多行形式上直接定义一个乘法altm（e；k）×altn（e；k）－→altm+n（e；k），以便下面的图表可以转换吗？

​                                               Vm(E∗) × Vn(E∗)          ∧       / Vm+n(E∗)
 vm（e）×vn（e）/vm+n（e）

​                                                             µm×µn                               µm+n
 礹m×礹n礹m+n

​                                          Altm(E;K) × Altn(E;K)       ∧   / Altm+n (E;K)
 altm（e；k）×altn（e；k）/altm+n（e；k）

As in the symmetric case, the answer is yes! The solution is to define this multiplication such that, for f ∈ Altm(E;K) and g ∈ Altn(E;K),
 和对称情况一样，答案是肯定的！解决方法是定义这个乘法，这样，对于f∈altm（e；k）和g∈altn（e；k），就

(f ∧ g)(u1,...,um+n) = X sgn(σ)f(uσ(1),...,uσ(m))g(uσ(m+1),...,uσ(m+n)), (∗∗)
 （f g）（u1，…，u m+n）=x sgn（σ）f（uσ（1），…，uσ（m））g（uσ（m+1），…，uσ（m+n）），（）

σ∈shuffle(m,n)
 σ∈洗牌（m，n）

where shuffle(m,n) consists of all (m,n)-“shuffles;” that is, permutations σ of {1,...m+n} such that σ(1) < ··· < σ(m) and σ(m+1) < ··· < σ(m+n). For example, when m = n = 1, we have
 式中，shuffle（m，n）由所有（m，n）-“shuffles”组成；即，置换σof 1，…m+n，这样，σ（1）<······<σ（m）和σ（m+1）<······<σ（m+n）。例如，当m=n=1时，我们有

(f ∧ g)(u,v) = f(u)g(v) − g(u)f(v).
 （f g）（u，v）=f（u）g（v）−g（u）f（v）。

When m = 1 and n ≥ 2, check that
 当m=1且n≥2时，检查

,
 ，

where the hat over the argument ui means that it should be omitted.
 其中，参数ui上的帽子意味着应该省略它。

Here is another explicit example. Suppose m = 2 and n = 1. Given , the multiplication structure on V(E∗) implies that (
 这是另一个明确的例子。假设m=2，n=1。给定，v（e）上的乘法结构意味着（

Furthermore, for u1,u2,u3,∈ E,
 此外，对于U1，U2，U3，∈e，

µ3(v1∗ ∧ v2∗ ∧ v3∗)(u1,u2,u3) = X sgn(σ)vσ∗(1)(u1)vσ∗(2)(u2)vσ∗(3)(u3)
 μ3（v1 v2 v3）（u1，u2，u3）=x sgn（σ）vσ（1）（u1）vσ（2）（u2）vσ（3）（u3）

σ∈S3
 σ∈S3

= v1∗(u1)v2∗(u2)v3∗(u3) − v1∗(u1)v3∗(u2)v2∗(u3) − v2∗(u1)v1∗(u2)v3∗(u3) + v2∗(u1)v3∗(u2)v1∗(u3)
 =v1（u1）v2（u2）v3（u3）−v1（u1）v3（u2）v2（u3）−v2（u1）v1（u2）v3（u3）+v2（u1）v3（u2）v1（u3）

\+ v3∗(u1)v1∗(u2)v2∗(u3) − v3∗(u1)v2∗(u2)v1∗(u3). Now the (2,1)- shuffles of {1,2,3} are the following three permutations, namely
 +v3（u1）v1（u2）v2（u3）−v3（u1）v2（u2）v1（u3）。现在1,2,3的（2,1）-洗牌是以下三种排列，即

​                                                 ,                          ,                           .
 、、。

If) and), then (∗∗) implies that
 如果）和），那么（）意味着

(f · g)(u1,u2,u3) = X sgn(σ)f(uσ(1),uσ(2))g(uσ(3))
 （f·g）（u1，u2，u3）=x sgn（σ）f（uσ（1），uσ（2））g（uσ（3））

σ∈shuffle(2,1)
 σ∈洗牌（2,1）

= f(u1,u2)g(u3) − f(u1,u3)g(u2) + f(u2,u3)g(u1)
 =f（u1，u2）g（u3）−f（u1，u3）g（u2）+f（u2，u3）g（u1）

= µ2(v1∗ ∧ v2∗)(u1,u2)µ1(v3∗)(u3) − µ2(v1∗ ∧ v2∗)(u1,u3)µ1(v3∗)(u2)
 =μ2（v1 v2）（u1，u2）μ1（v3）（u3）−μ2（v1 v2）（u1，u3）μ1（v3）（u2）

\+ µ2(v1∗ ∧ v2∗)(u2,u3)µ1(v3∗)(u1)
 +μ2（v1 v2）（u2，u3）μ1（v3）（u1）

= (v1∗(u1)v2∗(u2) − v2∗(u1)v1∗(u2))v3∗(u3)
 =（v1（u1）v2（u2）−v2（u1）v1（u2））v3（u3）

− (v1∗(u1)v2∗(u3) − v2∗(u1)v1∗(u3))v3∗(u2)
 −（v1（u1）v2（u3）−v2（u1）v1（u3））v3（u2）

\+ (v1∗(u2)v2∗(u3) − v2∗(u2)v1∗(u3))v3∗(u1) = µ3(v1∗ ∧ v2∗ ∧ v3∗)(u1,u2,u3).
 +（v1（u2）v2（u3）−v2（u2）v1（u3））v3（u1）=（v1 v2 v3）（u1、u2、u3）。

As a result of all this, the direct sum
 因此，直接和

Alt(E) = MAltn(E;K)
 alt（e）=maltn（e；k）

n≥0
 n＝0

is an algebra under the above multiplication, and this algebra is isomorphic to V(E∗). For the record we state
 是上面乘法下的代数，这个代数同构于v（e）。为了我们的记录

33.6. THE HODGE ∗-OPERATOR
 小精灵。霍奇-操作员

Proposition 33.14. When E is finite dimensional, the maps µ: Vn(E∗) −→ Altn(E;K) induced by the linear extensions of the maps given by
 提案33.14.当e为有限维时，图的μ：vn（e）−→altn（e；k）由以下公式给出的图的线性扩展所诱导：

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image035.gif)

yield a canonical isomorphism of algebras µ: V(E∗) −→ Alt(E), where the multiplication in Alt(E) is defined by the maps ∧: Altm(E;K) × Altn(E;K) −→ Altm+n(E;K), with
 生成代数的典型同构：v（e）−→alt（e），其中alt（e）中的乘法由映射：altm（e；k）×alt n（e；k）−→altm+n（e；k）定义，其中

(f ∧ g)(u1,...,um+n) = X sgn(σ)f(uσ(1),...,uσ(m))g(uσ(m+1),...,uσ(m+n)),
 （f g）（u1，…，u m+n）=x sgn（σ）f（uσ（1），…，uσ（m））g（uσ（m+1），…，uσ（m+n）），

σ∈shuffle(m,n)
 σ∈洗牌（m，n）

where shuffle(m,n) consists of all (m,n)-“shuffles,” that is, permutations σ of {1,...m+n} such that σ(1) < ··· < σ(m) and σ(m + 1) < ··· < σ(m + n).
 其中shuffle（m，n）由所有（m，n）-“shuffles”组成，即1，…m+n的置换σ，使得σ（1）<······<σ（m）和σ（m+1）<······<σ（m+n）。

Remark: The algebra V(E) is a graded algebra. Given two graded algebras E and F, we can make a new tensor product E ⊗b F, where E ⊗b F is equal to E ⊗ F as a vector space, but with a skew-commutative multiplication given by
 注：代数V（E）是一个等级代数。给定两个分次代数e和f，我们可以得到一个新的张量积e b f，其中e b f等于e f作为向量空间，但用下式给出的一个斜交换乘法

(a ⊗ b) ∧ (c ⊗ d) = (−1)deg(b)deg(c)(ac) ⊗ (bd),
 （a b）（c d）=（-1）deg（b）deg（c）（ac）（bd）、

where a ∈ Em,b ∈ Fp, c ∈ En,d ∈ Fq. Then, it can be shown that
 其中a∈em，b∈fp，c∈en，d∈fq。那么，可以看出

^(E ⊕ F) ∼= ^(E) ⊗b^(F).
 ^（e_f）b（f）。

## 33.6        The Hodge ∗-Operator  33.6 Hodge-操作员

In order to define a generalization of the Laplacian that applies to differential forms on a
 为了定义拉普拉斯的推广，它适用于

Riemannian manifold, we need to define isomorphisms
 黎曼流形，我们需要定义同构

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image037.gif)

for any Euclidean vector space V of dimension n and any k, with 0 ≤ k ≤ n. If h−,−i denotes the inner product on V , we define an inner product on Vk V , denoted h−,−i∧, by setting hu1 ∧ ··· ∧ uk,v1 ∧ ··· ∧ vki∧ = det(hui,vji),
 对于尺寸n的任何欧几里得向量空间v和任何k，0≤k≤n。如果h−，−i表示v上的内积，我们在vk v上定义内积，表示h−，−i，通过设置hu1············································

for all ui,vi ∈ V , and extending h−,−i∧ by bilinearity.
 对于所有用户界面，v i∈v，并通过双线性扩展h−、−i。

It is easy to show that if (e1,...,en) is an orthonormal basis of V , then the basis of Vk V consisting of the eI (where I = {i1,...,ik}, with 1 ≤ i1 < ··· < ik ≤ n) is an orthonormal basis of Vk V . Since the inner product on V induces an inner product on V ∗ (recall that , for all ω1,ω2 ∈ V ∗), we also get an inner product on Vk V ∗.
 很容易看出，如果（e1，…，en）是v的正态基，那么由ei组成的vk v的基（其中i=i1，…，ik，其中1≤i1<······<ik≤n）是vk v的正态基。由于v上的内积在v上诱导内积（回想一下，对于所有ω1，ω2∈v），我们也得到vk v上的内积。

Definition 33.6. An orientation of a vector space V of dimension n is given by the choice of some basis (e1,...,en). We say that a basis (u1,...,un) of V is positively oriented iff det(u1,...,un) > 0 (where det(u1,...,un) denotes the determinant of the matrix whose jth column consists of the coordinates of uj over the basis (e1,...,en)), otherwise it is negatively oriented. An oriented vector space is a vector space V together with an orientation of V .
 定义33.6.通过选择一些基（e1，…，en），给出了n维向量空间v的方向。我们说V的基（u1，…，un）是正向的，iff det（u1，…，un）>0（其中det（u1，…，un）表示矩阵的行列式，其jth列由基（e1，…，en）上的uj坐标组成），否则它是负向的。有向向量空间是向量空间V加上V的方向。

If V is oriented by the basis (e1,...,en), then V ∗ is oriented by the dual basis (
 如果V由基（e1，…，en）定向，则V由双基定向（

If σ is any permutation of {1,...,n}, then the basis (eσ(1),...,eσ(n)) has positive orientation iff the signature sgn(σ) of the permutation σ is even.
 如果σ是1，…，n的任意置换，则基（eσ（1），…，eσ（n））具有正方向，如果置换σ的签名sgn（σ）是偶数。

If V is an oriented vector space of dimension n, then we can define a linear isomorphism
 如果v是一个维数为n的定向向量空间，那么我们可以定义一个线性同构。

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image039.gif)

called the Hodge ∗-operator. The existence of this operator is guaranteed by the following proposition.
 称为hodge-运算符。这个算符的存在性由以下命题来保证。

Proposition 33.15. Let V be any oriented Euclidean vector space whose orientation is given by some chosen orthonormal basis (e1,...,en). For any alternating tensor α ∈ Vk V , there is a unique alternating tensor ∗α ∈ Vn−k V such that
 提案33.15。设V为任意定向欧几里得向量空间，其方向由选定的正交基（e1，…，en）给出。对于任何交变张量α∈v k v，都有一个唯一的交变张量α∈vn−k v，这样

α ∧ β = h∗α,βi∧ e1 ∧ ··· ∧ en
 αβ=Hα，βi e1···en

for all β ∈ Vn−k V . The alternating tensor ∗α is independent of the choice of the positive orthonormal basis (e1,...,en).
 对于所有β∈VN−K V。交替张量α与正正交基（e1，…，en）的选择无关。

Proof. Since Vn V has dimension 1, the alternating tensor e1 ∧ ··· ∧ en is a basis of Vn V . It follows that for any fixed α ∈ Vk V , the linear map λα from Vn−k V to Vn V given by
 证据。由于vn v的维数为1，交变张量e1····en是vn v的基础。由此可知，对于任何固定α∈v k v，从vn−k v到vn v的线性映射为

λα(β) = α ∧ β
 λα（β）=αβ

is of the form λα(β) = fα(β)e1 ∧ ··· ∧ en
 形式为λα（β）=fα（β）e1···en

for some linear form. But then, by the duality induced by the inner product h−,−i on Vn−k V , there is a unique vector ∗α ∈ Vn−k V such that
 对于某种线性形式。但是，由于内积h−、−i在vn−k v上诱导的对偶性，存在一个唯一的向量∮α∈vn−k v，这样

​                                               fλ(β) = h∗α,βi∧      for all β ∈ Vn−k V ,
 fλ（β）=hα，βi对于所有β∈vn−k v，

which implies that
 这意味着

α ∧ β = λα(β) = fα(β)e1 ∧ ··· ∧ en = h∗α,βi∧ e1 ∧ ··· ∧ en,
 αβ=λα（β）=fα（β）e1·····en=hα，βi e1····en，

as claimed. If () is any other positively oriented orthonormal basis, by Proposition
 如要求。如果（）是任何其他正方向正交基，通过命题

, since det(P) = 1 where P is the
 ，因为det（p）=1，其中p是

change of basis from () and both bases are positively oriented.                                                   
 基础从（）开始改变，两个基础都是正向的。

33.6. THE HODGE ∗-OPERATOR
 小精灵。霍奇-操作员

Definition 33.7. The operator ∗ from Vk V to Vn−k V defined by Proposition 33.15 is called the Hodge ∗-operator.
 定义33.7.由命题33.15定义的从v k v到vn−k v的算符称为hodge算符。

Obseve that the Hodge ∗-operator is linear.
 注意Hodge-运算符是线性的。

The Hodge ∗-operator is defined in terms of the orthonormal basis elements of VV as follows: For any increasing sequence (i1,...,ik) of elements ip ∈ {1,...,n}, if (j1,...,jn−k) is the increasing sequence of elements jq ∈ {1,...,n} such that
 Hodge-算符是根据vv的正交基元定义的，如下所示：对于元素ip 1，…，n的任何递增序列（i1，…，ik），如果（j1，…，jn−k）是元素jq 1，…，n的递增序列，这样

{i1,...,ik} ∪ {j1,...,jn−k} = {1,...,n},
 i1，…，ik j1，…，jn−k=1，…，n，

then
 然后

∗(ei1 ∧ ··· ∧ eik) = sign(i1,...ik,j1,...,jn−k)ej1 ∧ ··· ∧ ejn−k.
 （ei1···eik）=符号（i1，…ik，j1，…，jn−k）ej1···ejn−k。

In particular, for k = 0 and k = n, we have
 特别是，对于k=0和k=n，我们有

∗(1) =     e1 ∧ ··· ∧ en ∗(e1 ∧ ··· ∧ en)      =     1.
 （1）=e1······（e1····en）=1.

For example, if n = 3, we have
 例如，如果n=3，我们有

∗e1 = e2 ∧ e3
 e1=e2 e3

∗e2 = −e1 ∧ e3
 e2=−e1 e3

∗e3 = e1 ∧ e2
 e3=e1 e2

∗(e1 ∧ e2) = e3
 （e1 e2）=e3

∗(e1 ∧ e3) = −e2 ∗(e2 ∧ e3) = e1.
 （e1 e3）=-e2（e2 e3）=e1.

The Hodge ∗-operators ∗: Vk V → Vn−k V induce a linear map ∗: V(V ) → V(V ). We also have Hodge ∗-operators ∗: Vk V ∗ → Vn−k V ∗.
 Hodge-运算符：v k v→vn−k v诱导线性映射：v（v）→v（v）。我们还有hodge-operators：v k v→vn−k v。

The following proposition shows that the linear map ∗: V(V ) → V(V ) is an isomorphism.
 下面的命题表明线性映射：v（v）→v（v）是同构的。

Proposition 33.16. If V is any oriented vector space of dimension n, for every k with
 提案33.16。如果v是维度n的任何定向向量空间，对于每个k

0 ≤ k ≤ n, we have
 0≤k≤n，我们有

*(i)*       ∗∗ = (−id)k(n−k).
 =（−ID）K（N−K）。

*(ii)*     hx,yi∧ = ∗(x ∧ ∗y) = ∗(y ∧ ∗x), for all x,y ∈ Vk V .
 hx，yi=（x y）=（y x），对于所有x，y∈vk v。

Proof. (1) Let ( is an orthonormal basis of V . It is enough to check the identity on basis elements. We have
 证据。（1）Let（是v的正交基。只需根据基本元素检查身份即可。我们有

∗(ei1 ∧ ··· ∧ eik) = sign(i1,...ik,j1,...,jn−k)ej1 ∧ ··· ∧ ejn−k
 （ei1···eik）=符号（i1，…ik，j1，…，jn−k）ej1···ejn−k

and
 和

∗∗(ei1 ∧ ··· ∧ eik) = sign(i1,...ik,j1,...,jn−k) ∗(ej1 ∧ ··· ∧ ejn−k)
 （ei1···eik）=符号（i1，…ik，j1，…，jn−k）（ej1····ejn−k）

= sign(i1,...ik,j1,...,jn−k)sign(j1,...,jn−k,i1,...ik)ei1 ∧ ··· ∧ eik.
 =符号（i1，…ik，j1，…，jn−k）符号（j1，…，jn−k，i1，…ik）ei1···eik。

It is easy to see that
 很容易看到

sign(i1,...ik,j1,...,jn−k)sign(j1,...,jn−k,i1,...ik) = (−1)k(n−k),
 符号（i1，…ik，j1，…，jn−k）符号（j1，…，jn−k，i1，…ik）=（−1）k（n−k），

which yields
 会产生

∗∗(ei1 ∧ ··· ∧ eik) = (−1)k(n−k) ei1 ∧ ··· ∧ eik,
 （ei1····eik）=（−1）k（n−k）ei1····eik，

as claimed.
 如要求。

(ii) These identities are easily checked on basis elements; see Jost [98], Chapter 2, Lemma
 （ii）这些标识很容易根据元素进行检查；见Jost[98]，第2章，引理

2.1.1. In particular let
 2.1.1.尤其是让

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image041.gif)

xwhere (not equal to any is an orthonormal basis ofejq of by the orthonormality of the basis, this means theV . If x =6    y, hx,yi∧ = 0 since there is someth row ofeip of y   p
 式中（不等于任何）是ejq的正交基，由基的正交性决定，这意味着v。如果x=6y，hx，yi=0，因为y p的某一行EIP

(heil,ejsi) consists entirely of zeroes. Also x =6   y implies that y ∧ ∗x = 0 since
 （heil，ejsi）完全由零组成。同样，x=6y意味着y x=0，因为

∗x = sign(i1,...ik,l1,...,ln−k)el1 ∧ ··· ∧ eln−k,
 X=符号（I1，…Ik，L1，…，Ln−K）El1···Eln−K，

where els is the same as some ep in y. A similar argument shows that if x =6        y, x ∧ ∗y = 0.
 其中，els与y中的某个ep相同。类似的论点表明，如果x=6y，x y=0。

So now assume x = y. Then
 所以现在假设x=y。

∗(ei1 ∧ ··· ∧ eik ∧ ∗(ei1 ∧ ··· ∧ eik)) = ∗(e1 ∧ e2 ··· ∧ en) = 1 = hx,xi∧.   
 （E1）····εEk（1）＝HX，（X1）。

It is possible to express ∗(1) in terms of any basis (not necessarily orthonormal) of V .
 可以用V的任何基（不一定是正交）来表示（1）。

Proposition 33.17. If V is any finite-dimensional oriented vector space, for any basis (v!,...,vn) of V , we have
 提案33.17。如果v是任何有限维的定向向量空间，对于任何基（v！，…，Vn）的，我们有

.
 .

Proof. If (e1,...,en) is an orthonormal basis of V and (v1,...,vn) is any other basis of V , then hv1 ∧ ··· ∧ vn,v1 ∧ ··· ∧ vni∧ = det(hvi,vji),
 证据。如果（e1，…，en）是v的正交基，（v1，…，vn）是v的任何其他基，那么hv1·············································

and since
 从那以后

v1 ∧ ··· ∧ vn = det(A)e1 ∧ ··· ∧ en
 v1···vn=Det（a）e1····en


 

where A is the matrix expressing the vj in terms of the ei, we have hv1 ∧ ··· ∧ vn,v1 ∧ ··· ∧ vni∧ = det(A)2he1 ∧ ··· ∧ en,e1 ∧ ··· ∧ eni = det(A)2. As a consequence, det(A) = pdet(hvi,vji), and
 式中，a是用ei表示vj的矩阵，我们有hv1··································································因此，DET（A）=PDET（HVI、VJI），以及

q v1 ∧ ··· ∧ vn =    det(hvi,vji)e1 ∧ ··· ∧ en,
 q v1····vn=Det（hvi，vji）e1····en，

from which it follows that
 从中可以看出

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image043.gif)

​         (see Jost [98], Chapter 2, Lemma 2.1.3).                                                                                        
 （见Jost[98]，第2章，Lemma 2.1.3）。

##       33.7         Left and Right Hooks ~  33.7左右挂钩~

In this section all vector spaces are assumed to have finite dimension. Say dim(E) = n. Using our nonsingular pairing
 在本节中，假设所有向量空间都有有限维。假设dim（e）=n.使用我们的非奇异配对

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image045.gif)

defined on generators by
 在发电机上定义

,
 ，

we define various contraction operations (partial evaluation operators)
 我们定义了各种收缩操作（部分评估运算符）

​                                                                        y :                            (left hook)
 Y：（左钩）

and
 和

​                                                                      x :                            (right hook),
 X：（右钩）

as well as the versions obtained by replacing E by E∗ and E∗∗ by E. We begin with the left interior product or left hook, y.
 以及用e替换e得到的版本，用e替换e获得的版本。我们从左侧内饰产品或左侧挂钩y开始。

Let u ∈ Vp E. For any q such that p + q ≤ n, multiplication on the right by u is a linear map given by v 7→ v ∧ u
 设u∈v p e，对于任意q，如果p+q≤n，右边乘以u是由v 7→v_u给出的线性映射。

where v ∈ Vq E. The transpose of ∧R(u) yields a linear map
 式中v∈vq e，r（u）的转置产生一个线性映射。

,
 ，

which, using the isomorphisms and , can be viewed as a map
 它使用同构和，可以被看作是一个地图

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image047.gif)

given by
 给出者

z∗ 7→ z∗ ◦ ∧R(u),
 Z 7→Z R（U）

uwherey of z∧∗R∈(uV) defined byp+q E∗. We denote z∗ ◦ ∧R(u) by u y z∗. In terms of our pairing, the adjoint
 由p+q e定义的z r（uv）的公式。我们用u y z_表示z__r（u）。就我们的配对而言，

;
 ；

this in turn leads to the following definition.
 这反过来导致了以下定义。

Definition 33.8. Let u ∈ Vp E and z∗ ∈ Vp+q E∗. We define u y z∗ ∈ Vq E∗ to be q-vector uniquely determined by
 定义33.8.设u vp e和z vp+q e。我们将u y z∈vq e定义为唯一由

​                                                   hu y z∗,vi = hz∗,v ∧ ui,        for all v ∈ Vq E.
 对于所有v∈vq e，hu y z，vi=hz，v ui。

Remark: Note that to be precise the operator
 备注：请注意，准确地说，操作员

y : 
 Y：

depends of p,q, so we really defined a family of operators y p,q. This family of operators y p,q induces a map
 依赖于p，q，所以我们真的定义了一个算子家族y，p，q。这个算子家族y，p，q产生了一个映射

y : ^E × ^E∗ −→ ^E∗,
 Y：^E×E−→^E，

with y
 用Y

as defined before. The common practice is to omit the subscripts of y .
 如前所述。通常的做法是省略y的下标。

It is immediately verified that
 立即证实

(u ∧ v) y z∗ = u y (v y z∗),
 （u v）y z=u y（v y z），

for all u ∈ Vk E,v ∈ Vp−k E, z∗ ∈ Vp+q E∗ since h(u ∧ v) y z∗,wi = hz∗,w ∧ u ∧ vi = hv y z∗,w ∧ ui = hu y (v y z∗),wi,
 对于所有u v k e，v vp k e，z vp+q e，因为h（u v）y z，wi=hz，w u vi=hv y z，w ui=hu y（v y z），wi，

whenever w ∈ Vq E. This means that
 每当w∈vq e，这意味着

y : ^E × ^E∗ −→ ^E∗
 Y：^E×E−→^E

is a left action of the (noncommutative) ring VE with multiplication ∧ on VE∗, which makes VE∗ into a left VE-module.
 是（非交换）环ve的左操作，在ve上乘，使ve成为左ve模块。

By interchanging E and E∗ and using the isomorphism
 通过交换e和e并使用同构

,
 ，

we can also define some maps
 我们也可以定义一些地图

y : 
 Y：

and make the following definition.
 并做出以下定义。

Definition 33.9. Let u∗ ∈ Vp E∗, and z ∈ Vp+q E. We define u∗ y z ∈ Vq as the q-vector uniquely defined by
 定义33.9.设u vp e，z vp+q e，定义u y z vq为唯一由

​                                               hv∗ ∧ u∗,zi = hv∗,u∗ y zi,       for all v∗ ∈ Vq E∗.
 hv u，zi=hv，u y zi，对于所有v∈vq e。

As for the previous version, we have a family of operators y p,q which define an operator
 对于前一个版本，我们有一个运算符Y p，Q系列，它定义了一个运算符

y : ^E∗ × ^E −→ ^E.
 Y：^E×^E−→^E.

We easily verify that
 我们很容易证实

(u∗ ∧ v∗) y z = u∗ y (v∗ y z),
 （u v）y z=u y（v y z），

whenever u∗ ∈ Vk E∗, v∗ ∈ Vp−k E∗, and z ∈ Vp+q E; so this version of y is a left action of the ring VE∗ on VE which makes VE into a left VE∗-module.
 当u∈v k e，v∈vp−k e，z∈vp+q e时，y的这个版本是环ve on ve的左作用，使ve成为左ve模件。

In order to proceed any further we need some combinatorial properties of the basis of Vp E constructed from a basis (e1,...,en) of E. Recall that for any (nonempty) subset I ⊆ {1,...,n}, we let eI = ei1 ∧ ··· ∧ eip,
 为了进一步，我们需要从e的基（e1，…，e n）构造出vp e的基的一些组合性质。回想一下，对于任何（非空）子集i 1，…，n，我们让ei=e i 1····eip，

where I = {i1,...,ip} with i1 < ··· < ip. We also let e∅ = 1.
 其中，i=i1，…，ip with i1<·······<ip.我们也让e∅=1。

Given any two nonempty subsets H,L ⊆ {1,...,n} both listed in increasing order, say H = {h1 < ... < hp} and L = {`1 < ... < `q}, if H and L are disjoint, let H ∪ L be union of H and L considered as the ordered sequence
 考虑到任意两个非空子集h，l 1，…，n都按递增顺序列出，例如h=h1<…<hp and l=`1<…<`Q，如果h和l是不相交的，那么h l是h和l的并集，被认为是有序序列。

(h1,...,hp,`1,...,`q).
 （h1，…，hp，`1，…`q）。

Then let
 那就让

,
 ，

​                                                           ρH,L         (−1)ν      if H ∩ L = ∅,
 ρh，l（−1）ν，如果h l=∅，

where ν = |{(h,l) | (h,l) ∈ H × L, h > l}|.
 式中，ν=（h，l）（h，l）∈h×l，h>l。

Observe that when H∩L = ∅, |H| = p and |L| = q, the number ν is the number of inversions of the sequence
 观察H L=∅、H=P、L=Q时，数濉为序列的倒转数。

(h1, ··· , hp, `1, ··· , `q),
 （h1，···，hp，`1，···，`Q）

where an inversion is a pair (hi,`j) such that hi > `j.
 其中一个倒转是一对（hi，`j），这样hi>`j。

 Unless p + q = n, the function whose graph is given by
 除非p+q=n，否则其图由下式给出的函数

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image049.gif)

is not a permutation of {1,...,n}. We can view ν as a slight generalization of the notion of the number of inversions of a permutation.
 不是1，…，n的排列。我们可以把π看作是置换倒数概念的一个小小的推广。

Proposition 33.18. For any basis (e1,...,en) of E the following properties hold: (1) If H ∩ L = ∅, |H| = p, and |L| = q, then
 提案33.18。对于e的任何基（e1，…，en），以下属性保持不变：（1）如果h l=∅，h=p，l=q，则

ρH,LρL,H = (−1)ν(−1)pq−ν = (−1)pq.
 ρh，lρl，h=−1）ν（−1）pq−ν=−1）pq。

*(2)*    For H,L ⊆ {1,...,m} listed in increasing order, we have
 对于H，L 1，…，M按递增顺序列出，我们有

eH ∧ eL = ρH,LeH∪L.
 eh el=ρh，leh l.

Similarly, e∗H ∧ e∗L = ρH,Le∗H∪L.
 同样，e h e l=ρh，le h l。

*(3)*    For the left hook
 对于左钩子

y : ,
 Y：

we have
 我们有

eH y e∗L = 0  if H 6⊆ L eH y e∗L = ρL−H,He∗L−H      if H ⊆ L.
 e h y e l=0如果h 6 l eh y e l=ρl−h，he l−h如果h l。

*(4)*    For the left hook y : 
 对于左钩Y：

we have
 我们有

e∗H y eL = 0  if H 6⊆ L e∗H y eL = ρL−H,HeL−H if H ⊆ L.
 如果h 6 l e h y el=ρl−h，则e h y el=0；如果h l，则hel−h。

Proof. These are proved in Bourbaki [25] (Chapter III, §11, Section 11), but the proofs of (3) and (4) are very concise. We elaborate on the proofs of (2) and (4), the proof of (3) being similar.
 证据。这些在Bourbaki[25]中得到了证明（第三章第11节），但是（3）和（4）的证明非常简洁。我们详细阐述了（2）和（4）的证明，其中（3）的证明是相似的。

In (2) if H∩L =6 ∅, then eH ∧eL contains some vector twice and so eH ∧eL = 0. Otherwise, eH ∧ eL consists of eh1 ∧ ··· ∧ ehp ∧ e`1 ∧ ··· ∧ e`q,
 在（2）中，如果h l=6∅，那么eh el包含一些向量两次，因此eh el=0。否则，eh el由eh1····ehp e`1···e`q组成，

and to order the sequence of indices in increasing order we need to transpose any two indices (hi,`j) corresponding to an inversion, which yields ρH,LeH∪L.
 为了使指数序列按递增顺序排列，我们需要将对应于反演的任意两个指数（hi，`j）转置，得到ρh，leh l。

Let us now consider (4). We have |L| = p + q and |H| = p, and the q-vector is
 现在让我们考虑（4）。我们有l=p+q和h=p，q矢量是

characterized by
 特点是

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image051.gif)

for all v∗ ∈ Vq E∗. There are two cases.
 对于所有v∈vq e。有两种情况。

Case 1: H 6⊆ L. If so, no matter what v∗ ∈ Vq E∗ is, since H contains some index h not in L, the hth row ( )) of the determinant  must be zero, so hv∗ ∧ e∗H,eLi = 0 for all v∗ ∈ Vq E∗, and since the pairing is nongenerate, we must have e∗H y eL = 0.
 例1:h 6 l。如果是，那么不管v∈vq e是什么，因为h包含一些不在l中的指数h，行列式的hth行（））必须为零，所以h v e h，eli=0代表所有v∈vq e，并且由于配对是非一般的，我们必须有e h y e l=0。

Case 2: H ⊆ L. In this case, for v∗ = e∗L−H, by (2) we have
 案例2：H L。在这种情况下，对于V=E L−H，通过（2）我们得到

,
 ，

which yields
 会产生

he∗L−H,e∗H y eLi = ρL−H,H.
 h e l−h，e h y eli=ρl−h，h.

The q-vector can be written as a linear combinationwith |J| = q so
 q矢量可以写成一个线性组合，其中j=q so

.
 .

​        By definition of the pairing,               = 0 unless J = L − H, which means that
 根据配对的定义，=0，除非j=l−h，这意味着

,
 ，

​        so λL−H = ρL−H,H, as claimed.                                                                                                        
 因此，如权利要求所述，λl−h=ρl−h，h。

Using Proposition 33.18, we have the Proposition 33.19. For the left hook
 利用33.18号提案，我们得到33.19号提案。对于左钩子

y :,
 Y：

for every u ∈ E, x∗ ∈ Vq+1−s E∗, and y∗ ∈ Vs E∗, we have
 对于每一个u∈e，x∈vq+1−s e，和y∈vs e，我们有

u y (x∗ ∧ y∗) = (−1)s(u y x∗) ∧ y∗ + x∗ ∧ (u y y∗).
 u y（x y）=（-1）s（u y x）y+x（u y）。

Proof. We can prove the above identity assuming that x∗ and y∗ are of the form e∗I and e∗J using Proposition 33.18 and leave the details as an exercise for the reader. 
 证据。我们可以用命题33.18证明上述身份，假设x和y为e i和e j的形式，并将细节留给读者作为练习。

Thus, y : E×Vq+1 E∗ −→ Vq E∗ is almost an anti-derivation, except that the sign (−1)s is applied to the wrong factor.
 因此，y:e×vq+1 e−→vq e几乎是反派生的，除了符号（−1）s应用于错误的因子。

We have a similar identity for the other version of the left hook
 对于另一个版本的左钩子，我们有类似的身份

y : 
 Y：

namely u∗ y (x ∧ y) = (−1)s(u∗ y x) ∧ y + x ∧ (u∗ y y)
 即u y（x y）=（−1）s（u y x）y+x（u y）

for every u∗ ∈ E∗, x ∈ Vq+1−s E, and y ∈ Vs E.
 对于每一个u e，x vq+1 s e，y vs e。

An application of this formula when q = 3 and s = 2 yields an interesting equation. In this case, u∗ ∈ E∗ and x,y ∈ V2 E, so we get
 当q=3，s=2时，这个公式的应用产生了一个有趣的方程。在这种情况下，u∈e和x，y∈v2 e，我们得到

u∗ y (x ∧ y) = (u∗ y x) ∧ y + x ∧ (u∗ y y).
 u y（x y）=（u y x）y+x（u y）。

(In particular, foru∗ y x) ∧ x = x ∧x(u=∗ yyx, since), and we obtainx ∈ V2 E and u∗ y x ∈ E, Proposition 33.12 implies that
 （特别是，对于u y x）x=x x（u y x，since），我们得到x v2 e和u y x e，命题33.12暗示

​                                                             u∗ y (x ∧ x) = 2((u∗ y x) ∧ x).                                                 (†)
 u y（x x）=2（（u y x）x）。（†）

As a consequence, (u∗ y x) ∧ x = 0 iff u∗ y (x ∧ x) = 0. We will use this identity together with Proposition 33.25 to prove that a 2-vector x ∈ V2 E is decomposable iff x ∧ x = 0.
 因此，（u y x）x=0 iff u y（x x）=0。我们将利用这个恒等式和33.25命题来证明2向量x∈v2 e是可分解的iff x x=0。

It is also possible to define a right interior product or right hook x, using multiplication on the left rather than multiplication on the right. Then we use the maps
 也可以使用左边的乘法而不是右边的乘法来定义右边的内部积或右边的钩子x。然后我们用地图

x : 
 X：

to make the following definition.
 做出以下定义。

Definition 33.10. Let u ∈ Vp E and z∗ ∈ Vp+q E∗. We define z∗ x u ∈ Vq E∗ to be the q-vector uniquely defined as
 定义33.10.设u vp e和z vp+q e。我们将z x u∈vq e定义为唯一定义为

​                                                 hz∗ x u,vi = hz∗,u ∧ vi,            for all v ∈ Vq E.
 hz x u，vi=hz，u vi，对于所有v vq e。

This time we can prove that
 这次我们可以证明

z∗ x (u ∧ v) = (z∗ x u) x v,
 Z X（U V）=（Z X U）X V，

so the family of operators x p,q defines a right action
 因此，操作符x p，q系列定义了一个正确的动作。

x : ^E∗ × ^E −→ ^E∗
 x：^e×e−→^e

of the ring VE on VE∗ which makes VE∗ into a right VE-module. Similarly, we have maps
 把ve变成一个正确的ve模件。同样，我们有地图

x : 
 X：

which in turn leads to the following dual formation of the right hook.
 这反过来又导致了右钩子的以下双重形成。

Definition 33.11. Let u∗ ∈ Vp E∗ and z ∈ Vp+q E. We define zxu∗ ∈ Vq to be the q-vector uniquely defined by
 定义33.11.设u∈vp e和z∈vp+q e，定义zxu∈vq为

​                                             hu∗ ∧ v∗,zi = hv∗,z x u∗i,           for all v∗ ∈ Vq E∗.
 胡V，z i=hv，z x u i，对于所有的V∈vq e。

We can prove that
 我们可以证明

z x (u∗ ∧ v∗) = (z x u∗) x v∗,
 z x（u v）=（z x u）x v，

so the family of operators x p,q defines a right action
 因此，操作符x p，q系列定义了一个正确的动作。

x : ^E × ^E∗ −→ ^E
 x：^e×e−→^e

of the ring VE∗ on VE which makes VE into a right VE∗-module.
 在使ve成为一个右ve模块的ve环上。

Since the left hook y : Vp E × Vp+q E∗ −→ Vq E∗ is defined by hu y z∗,vi = hz∗,v ∧ ui, for all u ∈ Vp E, v ∈ Vq E and z∗ ∈ Vp+q E∗,
 由于左钩y:vp e×vp+q e−→vq e由hu y z，vi=hz，v ui定义，对于所有u∈vp e，v∈vq e和z∈vp+q e，

the right hook x : 
 右钩X：

by hz∗ x u,vi = hz∗,u ∧ vi, for all u ∈ Vp E, v ∈ Vq E, and z∗ ∈ Vp+q E∗, and v ∧ u = (−1)pqu ∧ v, we conclude that
 通过hz x u，vi=hz，u vi，对于所有u vp e，v v q e，和z vp+q e，和v u=−1）pqu v，我们得出：

z∗ x u = (−1)pq u y z∗.
 Z X U=（-1）PQ U Y Z。

Similarly, since
 同样，因为

​        hv∗∗ ∧∧uv∗∗,z,zii == hhvv∗∗,u,z∗xyuz∗ii,, for allfor all uu∗∗ ∈∈ VVpp EE∗∗,, vv∗∗ ∈∈ VVqq EE∗∗, andand zz∈∈VVpp++qqEE,
 hv uv，z，z ii==hhvv，u，z xyuz ii，，对于所有uu∈vvpp ee，vv∈vqq ee，and zz∈vvpp++qee，

hu and v∗ ∧ u∗ = (−1)pqu∗ ∧ v∗, we have
 Hu和V U=（-1）PQU V，我们有

z x u∗ = (−1)pq u∗ y z.
 Z x U=（−1）PQ U Y Z.

We summarize the above facts in the following proposition.
 我们将上述事实概括为以下命题。

Proposition 33.20. The following identities hold:
 提案33.20。以下标识保留：

z∗ x u = (−1)pq u y z∗  for all u ∈ Vp E and all z∗ ∈ Vp+q E∗ z x u∗ = (−1)pq u∗ y z       for all u∗ ∈ Vp E∗ and all z ∈ Vp+q E.
 z x u=−1）pq u y z对于所有u vp e和所有z vp+q e z x u=（-1）pq u y z对于所有u vp e和所有z vp+q e。

Therefore the left and right hooks are not independent, and in fact each one determines the other. As a consequence, we can restrict our attention to only one of the hooks, for example the left hook, but there are a few situations where it is nice to use both, for example in Proposition 33.23.
 因此，左钩和右钩不是独立的，事实上，每一个都决定着另一个。因此，我们只能将注意力限制在其中一个钩子上，例如左钩子，但在一些情况下，最好同时使用这两个钩子，例如在33.23号提案中。

A version of Proposition 33.18 holds for right hooks, but beware that the indices in ρL−H,H are permuted. This permutation has to do with the fact that the left hook and the right hook are related via a sign factor.
 建议33.18的一个版本适用于右钩，但要注意，ρl−h，h中的指数是排列的。这种排列与一个事实有关，即左钩子和右钩子是通过一个符号因子关联的。

Proposition 33.21. For any basis (e1,...,en) of E the following properties hold:
 提案33.21。对于e的任何基础（e1，…，en），以下属性保持不变：

*(1)*     For the right hook x : 
 对于右挂钩X：

we have
 我们有

eL x e∗H = 0   if H 6⊆ L eL x e∗H = ρH,L−HeL−H if H ⊆ L.
 如果h 6 l，则el x e h=0；如果h l，则l−hel−h。

*(2)*     For the right hook x : 
 对于右挂钩X：

we have
 我们有

e∗L x eH = 0   if H 6⊆ L e∗L x eH = ρH,L−He∗L−H      if H ⊆ L.
 如果h 6 l e l x eh=ρh，则e l x eh=0；如果h l，则l−he l−h。

Remark: Our definition of left hooks as left actions y : Vp E × Vp+q E∗ −→ Vq E∗ and y : Vp E∗×Vp+q E −→ Vq E and right hooks as right actions x : Vp+q E∗×Vp E −→ Vq E∗ and x: Vp+q E×Vp E∗ −→ Vq E is identical to the definition found in Fulton and Harris [69] (Appendix B). However, the reader should be aware that this is not a universally accepted notation. In fact, the left hook u∗ y z defined in Bourbaki [25] is our right hook z x u∗, up to the sign (−1)p(p−1)/2. This has to do with the fact that Bourbaki uses a different pairing which also involves an extra sign, namely
 备注：我们将左钩定义为左作用y:vp e×vp+q e−→vq e和y:vp e×vp+q e−→vq e和右钩定义为右作用x:vp+q e×vp e−→vq e和x:vp+q e×vp e−→vq e与Fulton和Harris[69]中的定义相同（附加九b）。然而，读者应该知道，这不是一个普遍接受的符号。实际上，在Bourbaki[25]中定义的左钩子u_y z是我们的右钩子z x u，直到符号（−1）p（p−1）/2。这是因为Bourbaki使用了一个不同的配对，它还包含一个额外的符号，即

hv∗,u∗ y zi = (−1)p(p−1)/2hu∗ ∧ v∗,zi.
 hv，u y zi=（-1）p（p−1）/2hu v，zi.

One of the side-effects of this choice is that Bourbaki’s version of Formula (4) of Proposition 33.18 (Bourbaki [25], Chapter III, page 168) is
 这种选择的一个副作用是，布尔巴基对33.18号提案（布尔巴基[25]，第三章，第168页）公式（4）的版本是

​                                              e∗H y eL = 0   if H ⊆6 L
 e h y e l=0，如果h 6 l

​                                           e∗H y eL = (−1)p(p−1)/2ρH,L−HeL−H  if H ⊆ L,
 e h y e l=（−1）p（p−1）/2ρh，l−hel−h，如果h l，

where |H| = p and |L| = p + q. This correspond to Formula (1) of Proposition 33.21 up to the sign factor (−1)p(p−1)/2, which we find horribly confusing. Curiously, an older edition of Bourbaki (1958) uses the same pairing as Fulton and Harris [69]. The reason (and the advantage) for this change of sign convention is not clear to us.
 式中h=p和l=p+q。这符合命题33.21的公式（1），直到符号因子（−1）p（p−1）/2，我们发现这令人非常困惑。奇怪的是，一个旧版本的Bourbaki（1958）使用了与Fulton和Harris相同的配对[69]。我们不清楚这种标志公约变更的原因（以及优势）。

We also have the following version of Proposition 33.19 for the right hook. Proposition 33.22. For the right hook
 我们还为右钩子提供了33.19号提案的以下版本。提案33.22。对于右钩子

x : ,
 X：

for every u ∈ E, x∗ ∈ Vr E∗, and y∗ ∈ Vq+1−r E∗, we have
 对于每个u∈e，x∈vr e，和y∈vq+1−r e，我们有

(x∗ ∧ y∗) x u = (x∗ x u) ∧ y∗ + (−1)rx∗ ∧ (y∗ x u).
 （x y）x u=（x x u）y+（-1）rx（y x u）。

​         Proof. A proof involving determinants can be found in Warner [180], Chapter 2.                    
 证据。华纳[180]第2章提供了一个涉及行列式的证明。

Thus, x : Vq+1 E∗ × E −→ Vq E∗ is an anti-derivation. A similar formula holds for the the right hook x : Vq+1 E × E∗ −→ Vq E, namely
 因此，x:vq+1e×e−→vq e是反派生的。右钩子x:vq+1 e×e−→vq e的类似公式成立，即

(x ∧ y) x u∗ = (x x u∗) ∧ y + (−1)rx ∧ (y x u∗),
 （x y）x u=（x x u）y+（-1）rx（y x u），

for every u∗ ∈ E, ∈ Vr E, and y ∈ Vq+1−r E. This formula is used by Shafarevitch [153] to define a hook, but beware that Shafarevitch use the left hook notation u∗ y x rather than the right hook notation. Shafarevitch uses the terminology convolution, which seems very unfortunate.
 对于每一个u e，vr e，和y vq+1−r e，shafarevitch[153]使用这个公式来定义一个钩子，但是要注意shafarevitch使用左钩子符号u y x而不是右钩子符号。Shafarevitch使用了卷积这个术语，这看起来很不幸。

For u ∈ E, the right hook z∗ x u is also denoted i(u)z∗, and called insertion operator or interior product. This operator plays an important role in differential geometry.
 对于u∈e，右钩z x u也表示i（u）z，称为插入运算符或内部积。这个算符在微分几何中起着重要作用。

Definition 33.12. Let u ∈ E and z∗ ∈ Vn+1(E∗). If we view z∗ as an alternating multilinear map in Altn+1(E;K), then we define i(u)z∗ ∈ Altn(E;K) as given by
 定义33.12。设u e和z vn+1（e）。如果我们把z看作Altn+1（e；k）中的交替多行映射，那么我们定义i（u）z∈Altn（e；k），如下所示：

(i(u)z∗)(v1,...,vn) = z∗(u,v1,...,vn).
 （i（u）z）（v1，…，vn）=z（u，v1，…，vn）。

Using the left hook y and the right hook x we can define two linear maps γ: Vp E → Vn−p E∗ and δ: Vp E∗ → Vn−p E as follows:
 使用左钩Y和右钩X，我们可以定义两个线性映射γ：vp e→vn−p e和δ：vp e→vn−p e，如下所示：

Definition 33.13. For any basis (e1,...,en) of E, if we let M = {1,...,n}, e = e1 ∧···∧en, and, define γ: Vp E → Vn−p E∗ and δ: Vp E∗ → Vn−p E as
 定义33.13.对于e的任何基（e1，…，e n），如果我们让m=1，…，n，e=e1···en，并定义γ：vp e→vn−p e和δ：vp e→vn−p e为

​                                                        γ(u) = u y e∗    and    δ(v∗) = e x v∗,
 γ（u）=u y e和δ（v）=e x v，

for all u ∈ Vp E and all v∗ ∈ Vp E∗.
 对于所有u vp e和所有v vp e。

Proposition 33.23. The linear maps γ: Vp E → Vn−p E∗ and δ: Vp E∗ → Vn−p E are isomorphims, and γ−1 = δ. The isomorphisms γ and δ map decomposable vectors to decomposable vectors. Furthermore, if z ∈ Vp E is decomposable, say z = u1 ∧ ··· ∧ up for some ui ∈ E, then  for some , and for all i,j. A similar property holds for is any other basis of E and γ0 : Vp E → Vn−p E∗ and δ0 : Vp E∗ → Vn−p E are the corresponding isomorphisms, then γ0 = λγ and δ0 = λ−1δ for some nonzero λ ∈ K.
 提案33.23。线性映射γ：vp e→vn−p e和δ：vp e→vn−p e是同构的，γ−1=δ。同构γ和δ映射可分解向量到可分解向量。此外，如果z∈vp e是可分解的，假设z=u1······向上表示某些ui∈e，那么对于一些i，j，对于所有i，j，一个相似的性质持有的是e的任何其他基，而γ0:vp e→vn−p e和δ0:vp e→vn−p e是相应的同构，那么γ0=γ和δ对于一些非零的λ∈k，0=λ−1δ。

Proof. Using Propositions 33.18 and 33.21, for any subset J ⊆ {1,...,n} = M such that |J| = p, we have
 证据。使用命题33.18和33.21，对于任何子集j 1，…，n=m，这样j=p，我们

​                                                                                                             and .
 而且。

Thus, δ ◦ γ(eJ) = ρM−J,JρM−J,JeJ = eJ,
 因此，δγ（ej）=ρm−j，jρm−j，jej=ej，

since ρM−J,J = ±1. A similar result holds for γ ◦ δ. This implies that
 因为ρm−j，j=±1.同样的结果也适用于γδ。这意味着

​                                                             δ ◦ γ = id    and    γ ◦ δ = id.
 δγ=id和γδ=id。

Thus, γ and δ are inverse isomorphisms.
 因此，γ和δ是逆同构。

If z ∈ Vp E is decomposable, then z = u1 ∧ ··· ∧ up where u1,...,up are linearly independent since z = 06 , and we can pick a basis of E of the form (u1,...,un). Then the above formulae show that
 如果z∈vp e是可分解的，那么z=u1·····up，其中u1，…，up自z=06以来是线性独立的，我们可以选取形式（u1，…，un）的e的基。上述公式表明

.
 .

Since () is the dual basis of (u1,...,un), we have) is any other basis of E, because Vn E has dimension 1, we have
 因为（）是（u1，…，un）的对偶基，我们有）是e的任何其他基，因为vn e有维1，我们有

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image053.gif)

​         for some nonzero λ ∈ K, and the rest is trivial.                                                                             
 对于一些非零的λ∈k，其余的都是平凡的。

Applying Proposition 33.23 to the case where p = n − 1, the isomorphism γ: Vn−1 E → V1 E∗ maps indecomposable vectors in Vn−1 E to indecomposable vectors in V1 E∗ = E∗. But every vector in E∗ is decomposable, so every vector in Vn−1 E is decomposable.
 将命题33.23应用于p=n-1的情况，同构γ：vn-1e→v1e将vn-1e中的不可分解矢量映射到v1e=e中的不可分解矢量。但e中的每一个向量都是可分解的，所以vn-1e中的每一个向量都是可分解的。

Corollary 33.24. If E is a finite-dimensional vector space, then every vector in Vn−1 E is decomposable.
 推论33.24。如果e是一个有限维向量空间，那么vn-1e中的每个向量都是可分解的。


 

33.8. TESTING DECOMPOSABILITY ~
 33.8。测试可分解性~

## 33.8         Testing Decomposability ~  33.8测试可分解性~

We are now ready to tackle the problem of finding criteria for decomposability. Such criteria will use the left hook. Once again, in this section all vector spaces are assumed to have finite dimension. But before stating our criteria, we need a few preliminary results.
 我们现在已经准备好解决寻找可分解性标准的问题。这样的标准将使用左钩子。再一次，在这一节中，假设所有向量空间都有有限维。但在说明我们的标准之前，我们需要一些初步的结果。

Proposition 33.25. Given z ∈ Vp E with z = 06 , the smallest vector space W ⊆ E such that z ∈ Vp W is generated by the vectors of the form
 提案33.25。给定z∈vp e，z=06，最小向量空间w e，使z∈vp w由形式的向量生成。

​                                                    u∗ y z,         with u∗ ∈ Vp−1 E∗.
 u y z，其中u∈vp−1 e。

Proof. First let W be any subspace such that z ∈ Vp(W) and let (e1,...,er,er+1,...,en) be a basis of E such that (e1,...,er) is a basis of W. Then, 
 证据。首先让w是任何子空间，使得z∈vp（w）和let（e1，…，er，er+1，…，en）是e的基础，这样（e1，…，er）是w的基础。

and |I| = p − 1, and z = PJ µJeJ, where J ⊆ {1,...,r} and |J| = p ≤ r. It follows immediately from the formula of Proposition 33.18 (4), namely
 和i=p−1，z=p j_jej，其中j 1，…，r和j=p≤r。它立即从命题33.18（4）的公式中得出，即

e∗I y eJ = ρJ−I,JeJ−I,
 e i y ej=ρj−i，jej−i，

that u∗ y z ∈ W, since J − I ⊆ {1,...,r}.
 u y z w，因为j 1，…，r。

Next we prove that if W is the smallest subspace of E such that z ∈ Vp(W), then W is generated by the vectors of the form u∗ y z, where u∗ ∈ Vp−1 E∗. Suppose not. Then the vectors u∗ y z with u∗ ∈ Vp−1 E∗ span a proper subspace U of W. We prove that for every subspace W 0 of W with dim(W 0) = dim(W) − 1 = r − 1, it is not possible that u∗ y z ∈ W 0 for all u∗ ∈ Vp−1 E∗. But then, as U is a proper subspace of W, it is contained in some subspace W 0 with dim(W 0) = r − 1, and we have a contradiction.
 然后证明，如果w是e的最小子空间，使得z∈vp（w），那么w是由形式为u y z的向量生成的，其中u∈vp−1e。假设不是。然后，带u的向量u y z∈vp−1 e跨越W的一个合适的子空间u，我们证明了对于带dim（w 0）=dim（w）−1=r−1的W的每个子空间w 0，u y z∈w 0不可能代表所有u∈vp−1 e。但是，由于u是w的一个合适的子空间，它包含在一些子空间w 0中，其中dim（w0）=r-1，我们有一个矛盾。

AnyLetz ∈wV∈p(WW−) can be written asW 0 and pick a basis ofz = z0W+ formed by a basis (w ∧ z00, where z0 ∈ eV1,...,ep W 0 andr−1)zof00 ∈WV0 pand−1 Ww0., and since W is the smallest subspace containing z, we have z00 = 06 . Consequently, if we write z00 = PI λIeI in terms of the basis (e1,...,er−1) of W 0, there is some eI, with I ⊆ { } I| 1, so that the coefficient λI is nonzero. Now, using any basis of E 1,...,er−1,w), by Proposition 33.18 (4), we see that
 Anyletz∈wv∈p（w w−）可以写成w 0，并选取由基（w z00，其中z0∈ev1，…，ep w 0 andr−1）形成的z=z0w+的基，zof00∈wv0 p and−1 ww0，由于w是包含z的最小子空间，所以z00=06。因此，如果我们根据w 0的基（e1，…，er−1）写出z00=piλi ei，则存在一些ei，其中i i 1，因此系数λi不为零。现在，根据命题33.18（4），使用e 1，…，er-1，w的任何基础，我们看到

​                                                   e∗I y (w ∧ eI) = λw,          λ = ±1.
 e i y（w ei）=λw，λ=±1.

It follows that
 接下来是

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image055.gif)

with, which shows that . Therefore, W is indeed generated by the vectors of the form u∗ y z, where u∗ ∈ Vp−1 E∗. 
 有，这就说明了。因此，w确实是由形式为u y z的向量生成的，其中u∈vp−1 e。

To help understand Proposition 33.25, let E be the vector space with basis {e1,e2,e3,e4} and z = e1 ∧ e2 + e2 ∧ e3. Note that z ∈ V2 E. To find the smallest vector space W ⊆ E such that z ∈ V2 W, we calculate u∗ y z, where u∗ ∈ V1 E∗. The multilinearity of y implies it is enough to calculate u∗ y z for . Proposition 33.18 (4) implies that
 为了有助于理解33.25号提案，让e作为基e1、e2、e3、e4和z=e1 e2+e2 e3的向量空间。注意z∈v2 e。为了找到最小的向量空间w e，使z∈v2 w，我们计算u y z，其中u∈v1e。y的多重性意味着它足以计算u y z。提案33.18（4）意味着

e∗1 y z = e∗1 y (e1 ∧ e2 + e2 ∧ e3) = e1∗ y e1 ∧ e2 = −e2 e∗2 y z = e∗2 y (e1 ∧ e2 + e2 ∧ e3) = e1 − e3 e∗3 y z = e∗3 y (e1 ∧ e2 + e2 ∧ e3) = e3∗ y e2 ∧ e3 = e2 e∗4 y z = e∗4 y (e1 ∧ e2 + e2 ∧ e3) = 0.
 e 1 y z=e 1 y（e1 e2+e2 e3）=e1 y e1 e2；2 y z=e 2 y（e1 e2+e2；e3；3 y z=e 3 y（e1；e2+e2 e3）=e3 3 y（e1 e2+e2+e2 4 y z=e 4 y（e1 e2+e2 e3）=0.

Thus W is the two-dimensional vector space generated by the basis {e2,e1 − e3}. This is not surprising since z = −e2 ∧ (e1 − e3) and is in fact decomposable. As this example demonstrates, the action of the left hook provides a way of extracting a basis of W from z. Proposition 33.25 implies the following corollary.
 因此w是基e2，e1−e3生成的二维矢量空间。这并不奇怪，因为z=−e2（e1−e3）实际上是可分解的。如本例所示，左钩子的作用提供了一种从z中提取w的基础的方法。命题33.25暗示了以下推论。

Corollary 33.26. Any nonzero z ∈ Vp E is decomposable iff the smallest subspace W of E such that z ∈ Vp W has dimension p. Furthermore, if z = u1 ∧···∧up is decomposable, then (u1,...,up) is a basis of the smallest subspace W of E such that z ∈ Vp W
 推论33.26。任何非零的z∈vp e都是可分解的，只要e的最小子空间w使z∈vp w具有维数p，而且，如果z=u1·····up是可分解的，那么（u1，…，up）是e的最小子空间w的基础，这样z∈vp w

Proof. If dim(W) = p, then for any basis (e1,...,ep) of W we know that Vp W has e1∧···∧ep has a basis, and thus has dimension 1. Since z ∈ Vp W, we have z = λe1 ∧ ··· ∧ ep for some nonzero λ, so z is decomposable.
 证据。如果dim（w）=p，那么对于w的任何基（e1，…，ep），我们知道vp w具有e1·······························由于z∈vp w，对于一些非零的λ，我们有z=λe1···ep，因此z是可分解的。

Conversely assume that z ∈ Vp W is nonzero and decomposable. Then, z = u1 ∧···∧up, and since z = 06 , by Proposition 33.8 (u1,...,up) are linearly independent. Then for any
 相反地，假设z∈vp w为非零且可分解。然后，z=u1······向上，由于z=06，由33.8（u1，…，向上）命题是线性独立的。那么对于任何

(where u∗i is omitted), we have
 （省略u i），我们有

,
 ，

so by Proposition 33.25 we have ui ∈ W for i = 1,...,p. This shows that dim(W) ≥ p, but since z = u1 ∧ ··· ∧ up, we have dim(W) = p, which means that (u1,...,up) is a basis of W.    
 因此，在33.25号命题中，我们有i=1，…，p的ui∈w，这表明dim（w）≥p，但由于z=u1······up，我们有dim（w）=p，这意味着（u1，…，up）是w的基础。

Finally we are ready to state and prove the criterion for decomposability with respect to left hooks.
 最后，我们准备说明并证明左钩子的可分解性准则。

Proposition 33.27. Any nonzero z ∈ Vp E is decomposable iff
 提案33.27。任何非零z∈vp e都是可分解的iff

​                                           (u∗ y z) ∧ z = 0,          for all u∗ ∈ Vp−1 E∗.
 （u y z）z=0，对于所有u∈vp−1 e。

Proof. First assume that z ∈ Vp E is decomposable. If so, by Corollary 33.26, the smallest subspace W of E such that z ∈ Vp W has dimension p, so we have z = e1 ∧ ··· ∧ ep where e1,...,ep form a basis of W. By Proposition 33.25, for every u∗ ∈ Vp−1 E∗, we have u∗ y z ∈ W, so each u∗ y z is a linear combination of the ei’s, say
 证据。首先假设z∈vp e是可分解的。如果是这样，由推论33.26，e的最小子空间w，使z∈vp w具有维数p，那么我们得到z=e1···ep，其中e1，…，ep构成w的基础。由命题33.25，对于每个u∈vp−1e，我们得到u y z∈w，因此每个u y z是ei的线性组合，说

u∗ y z = α1e1 + ··· + αpep,
 u y z=α1e1+····+αpep，

33.8. TESTING DECOMPOSABILITY ~
 33.8。测试可分解性~

and p
 和P

(u∗ y z) ∧ z = Xαiei ∧ e1 ∧ ··· ∧ ei ∧ ··· ∧ ep = 0.
 （u y z）z=xαiei e1····ei···ep=0.

i=1
 i＝1

Now assume that (u∗ yz)∧z = 0 for all u∗ ∈ Vp−1 E∗, and that dim(W) = m > p, where W is the smallest subspace of E such that z ∈ Vp W If e1,...,em is a basis of W, then we have z = PI λIeI, where I ⊆ {1,...,m} and |I| = p. Recall that z = 06 , and so, some λI is nonzero. By Proposition 33.25, each ei can be written as u∗ y z for some u∗ ∈ Vp−1 E∗, and since (u∗ y z) ∧ z = 0 for all u∗ ∈ Vp−1 E∗, we get
 现在假设（u yz）z=0表示所有u∈vp−1 e，并且dim（w）=m>p，其中w是e的最小子空间，因此z∈vp w如果e1，…，em是w的基础，那么我们有z=p iλiei，其中i 1，…，m和i p。回想一下z=06，因此，一些λi是非零的。根据命题33.25，对于某些u∈vp−1 e，每个ei可以写成u y z，由于（u y z）z=0对于所有u∈vp−1 e，我们得到

​                                                     ej ∧ z = 0    for        j = 1,...,m.
 j=1，…，m时，ej z=0。

By wedging z = PI λIeI with each ej, as m > p, we deduce λI = 0 for all I, so z = 0, a contradiction. Therefore, m = p and Corollary 33.26 implies that z is decomposable. 
 通过将z=p iλiei与每个ej楔入，作为m>p，我们推导出所有i的λi=0，因此z=0，这是一个矛盾。因此，m=p和推论33.26意味着z是可分解的。

As a corollary of Proposition 33.27 we obtain the following fact that we stated earlier without proof.
 作为第33.27号命题的推论，我们得出了以下事实，即我们在前面陈述时没有证据。

Proposition 33.28. Given any vector space E of dimension n, a vector x ∈ V2 E is decomposable iff x ∧ x = 0.
 提案33.28。在任意维为n的向量空间e下，向量x∈v2 e是可分解的iff x x=0。

Proof. Recall that as an application of Proposition 33.19 we proved the formula (†), namely
 证据。回想一下，作为命题33.19的一个应用，我们证明了公式（†），即

u∗ y (x ∧ x) = 2((u∗ y x) ∧ x)
 u y（x x）=2（（u y x）x）

for all x ∈ V2 E and all u∗ ∈ E∗. As a consequence, (u∗ y x) ∧ x = 0 iff u∗ y (x ∧ x) = 0. By Proposition 33.27, the 2-vector x is decomposable iff u∗ y (x ∧ x) = 0 for all u∗ ∈ E∗ iff x ∧ x = 0. Therefore, a 2-vector x is decomposable iff x ∧ x = 0. 
 对于所有x v2 e和所有u e。因此，（u y x）x=0 iff u y（x x）=0。根据命题33.27，对于所有u∈e iff x x=0，2向量x是可分解的。因此，2向量x是可分解的iff x x=0。

As an application of Proposition 33.28, assume that dim(E) = 3 and that (e1,e2,e3) is a basis of E. Then any 2-vector x ∈ V2 E is of the form
 作为33.28号命题的一个应用，假设dim（e）=3，并且（e1，e2，e3）是e的基础，那么任何2向量x∈v2 e的形式

x = αe1 ∧ e2 + βe1 ∧ e3 + γe2 ∧ e3.
 x=αe1 e2+βe1 e3+γe2 e3。

We have x ∧ x = (αe1 ∧ e2 + βe1 ∧ e3 + γe2 ∧ e3) ∧ (αe1 ∧ e2 + βe1 ∧ e3 + γe2 ∧ e3) = 0,
 我们得到x x=（αe1 e2+βe1 e3+γe2 e3）（αe1 e2+βe1 e3+γe2 e3）=0，

because all the terms involved are of the form cei1 ∧ei2 ∧ei3 ∧ei4 with i1,i2,i3,i4 ∈ {1,2,3}, and so at least two of these indices are identical. Therefore, every 2-vector x = αe1 ∧ e2 + βe1 ∧ e3 + γe2 ∧ e3 is decomposable, although this not obvious at first glance. For example,
 因为所有涉及的术语都是CEI1 EI2 EI3 EI4的形式，其中I1、I2、I3、I4 1、2、3，因此至少有两个指数是相同的。因此，每2个向量x=αe1 e2+βe1 e3+γe2 e3都是可分解的，尽管乍一看这并不明显。例如，

e1 ∧ e2 + e1 ∧ e3 + e2 ∧ e3 = (e1 + e2) ∧ (e2 + e3).
 e1 e2+e1 e3+e2 e3=（e1+e2）（e2+e3）。

We now show that Proposition 33.27 yields an equational criterion for the decomposability of an alternating tensor z ∈ Vp E.
 我们现在证明，命题33.27给出了交替张量z∈vp e可分解性的一个等式准则。

## 33.9     The Grassmann-Plu¨cker’s Equations and Grassmannian Manifolds ~  33.9格拉斯曼PLU–克尔方程和格拉斯曼流形~

We follow an argument adapted from Bourbaki [25] (Chapter III, §11, Section 13).
 我们遵循一个改编自Bourbaki[25]的论点（第三章，第11节，第13节）。

Let E be a vector space of dimensions n, let (e1,...,en) be a basis of E, and let (
 设e为n维的向量空间，设（e1，…，en）为e的基，设（

be its dual basis.decomposable. By Proposition 33.27, the vectorOur objective is to determine whether a nonzero vectorz is decomposable iff (u∗ yz) zz ∈= 0Vfor allp E is u∗ ∈ Vp−1 E∗. We can let u∗ range over a basis of Vp−1 E∗, and then the conditions are∧
 是它的双重基础。可分解。根据命题33.27，向量机的目标是确定非零向量是否可分解iff（u yz）zz∈=0vforallp e是u∈vp−1e。我们可以让u范围在vp−1 e的基础上，然后条件是

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image057.gif)

for all H ⊆ {1,...,n}, with |H| = p − 1. Since (e∗H y z) ∧ z ∈ Vp+1 E, this is equivalent to
 对于所有H 1，…，N，其中H=P−1。由于（e h y z）z∈vp+1e，这相当于

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image059.gif)

for all H,J ⊆ {0| =1,...,np, Formulae (2) and (4) of Proposition 33.18 show that}, with |H| = p − 1 and |J| = p + 1. Then, for all I,I0 ⊆ {1,...,n} with |I| = |I
 对于所有h，j 0=1，…，np，命题33.18的公式（2）和（4）表明，其中h=p−1和j=p+1。那么，对于所有的i，i0 1，…，n with i=i

he∗J,(e∗H y eI) ∧ eI0i = 0,
 他j，（e h y ei）ei0i=0，

unless there is some i ∈ {1,...,n} such that
 除非有一些i∈1，…，n这样

​                                                        I − H = {i},         J − I0 = {i}.
 I−H I，J−I0 I。

In this case, I = H ∪ {i} and I0 = J − {i}, and using Formulae (2) and (4) of Proposition 33.18, we have
 在这种情况下，i=h i和i0=j−i，利用33.18号提案的公式（2）和（4），我们得出

.
 .

If we let
 如果我们让

,
 ，

we have = +1 if the parity of the number of j ∈ J such that1 otherwise.j < i is the same as the parity of the number of h ∈ H such that h < i, and
 如果j∈j的个数的奇偶性为1，则为=+1，否则为1。j<i与h∈h的个数的奇偶性相同，因此h<i，并且

Finally we obtain the following criterion in terms of quadratic equations (Plu¨cker’s equations) for the decomposability of an alternating tensor.
 最后，我们用二次方程（plu–cker方程）得到了交变张量可分解性的以下准则。

Proposition 33.29.ditions for z 6= 0 to be decomposable are(Grassmann-Plu¨cker’s Equations) For z = PI λIeI ∈ Vp E, the con-
 命题33.29.z 6=0可分解的条件是（格拉斯曼-普卢克方程）对于z=piλiei∈vp e，the con-

,
 ，

with, for all H,J ⊆ {1,...,n} such that |H| = p−1, |J| = p+1, and all i ∈ J − H.
 对于所有h，j 1，…，n使得h=p−1，j=p+1，并且所有i∈j−h。

33.9. THE GRASSMANN-PLUCKER’S EQUATIONS AND GRASSMANNIANS¨                    ~
 33.9。格拉斯曼-普勒方程与格拉斯曼方程~

Using the above criterion, it is a good exercise to reprove that if dim(E) = n, then every tensor in Vn−1(E) is decomposable. We already proved this fact as a corollary of Proposition 33.23.
 利用上述标准，我们可以很好地证明，如果dim（e）=n，那么vn−1（e）中的每个张量都是可分解的。我们已经证明了这一事实，作为33.23号命题的推论。

Given any z = PI λIeI ∈ Vp E where dim(E) = n, the family of scalars (λI) (with I = < ip} ⊆ {1,...,n} listed in increasing order) is called the Plu¨cker coordinates of .The Grassmann-Plu¨cker’s equations give necessary and sufficient conditions for any nonzero z to be decomposable.
 给定任意z=piλi e i∈vp e，其中dim（e）=n，标量族（λi）（i=<ip 1，…，n按递增顺序列出）称为的plu cker坐标。格拉斯曼plu¨cker方程给出了任何非零z可分解的必要和充分条件。

For example, when dim(E) = n = 4 and p = 2, these equations reduce to the single equation λ12λ34 − λ13λ24 + λ14λ23 = 0.
 例如，当dim（e）=n=4和p=2时，这些方程简化为单个方程λ12λ34−λ13λ24+λ14λ23=0。

However, it should be noted that the equations given by Proposition 33.29 are not independent in general.
 然而，应当注意的是，命题33.29给出的方程一般不独立。

We are now in the position to prove that the Grassmannian G(p,n) can be embedded in the projective space,
 我们现在可以证明格拉斯曼G（p，n）可以嵌入到射影空间中，

For any n ≥ 1 and any k with 1 ≤ p ≤ n, recall that the Grassmannian G(p,n) is the set of all linear p-dimensional subspaces of Rn (also called p-planes). Any p-dimensional subspace U of Rn is spanned by p linearly independent vectors u1,...,up in Rn; write U = span(u1,...,uk). By Proposition 33.8, (u1,...,up) are linearly independent iff u1 ∧···∧up =6 0. If (v1,...,vp) are any other linearly independent vectors spanning U, then we have
 对于任何n≥1和任何k（1≤p≤n），回想格拉斯曼尼亚g（p，n）是RN的所有线性p维子空间（也称为p平面）的集合。RN的任何p维子空间u都由p线性无关向量u1，…，向上在rn中表示；写u=span（u1，…，uk）。根据命题33.8，（u1，…，up）是线性独立的iff u1····up=6 0。如果（v1，…，vp）是跨越u的任何其他线性无关向量，那么我们有

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image061.gif)

for some aij ∈ R, and by Proposition 33.2
 对于某些aij∈r，并通过命题33.2

v1 ∧ ··· ∧ vp = det(A)u1 ∧ ··· ∧ up,
 v1···vp=Det（a）U1····向上，

where A = (aij). As a consequence, we can define a map such that for any k-plane U, for any basis (u1,...,up) of U,
 其中a=（aij）。因此，我们可以定义一个图，对于任何k平面u，对于u的任何基（u1，…，向上）。

iG(U) = [u1 ∧ ··· ∧ up],
 ig（u）=[u1·····向上]，

the point of given by the one-dimensional subspace of spanned by u1 ∧···∧up.
 由u1·····向上跨越的一维子空间给出的点。

Proposition 33.30. The map  is injective.
 提案33.30。地图是注射剂。

Proof. Let U and V be any two p-planes and assume that iG(U) = iG(V ). This means that there is a basis (u1,...,up) of U and a basis (v1,...,vp) of V such that
 证据。设u和v为任意两个p平面，并假定ig（u）=ig（v）。这意味着有一个u的基（u1，…，up）和一个v的基（v1，…，vp），这样

v1 ∧ ··· ∧ vp = cu1 ∧ ··· ∧ up
 v1···vp=cu1·····向上

for some nonzero c ∈ R. The above implies that the smallest subspaces W and W 0 of Rn such that u1 ∧ ··· ∧ up ∈ Vp W and v1 ∧ ··· ∧ vp ∈ Vp W 0 are identical, so W = W 0. By
 对于一些非零c∈r，上面暗示了RN的最小子空间w和w 0，使得u1··························vp w 0和v1··········vp w 0是相同的，所以w=w 0。通过

Corollary 33.26, this smallest subspace W has both (u1,...,up) and (v1,...,vp) as bases, so the vj are linear combinations of the ui (and vice-versa), and U = V . Since any nonzero z ∈ Vp Rn can be uniquely written as
 推论33.26，这个最小的子空间w以（u1，…，up）和（v1，…，vp）为基，所以vj是ui的线性组合（反之亦然），u=v。因为任何非零z∈vp rn可以唯一地写为

z = XλIeI
 Z=xλiei

I
 我

in terms of its Plu¨cker coordinates (λI), every point of  is defined by the Plu¨cker coordinates (λI) viewed as homogeneous coordinates. The points of  corresponding to one-dimensional spaces associated with decomposable alternating p-tensors are the points whose coordinates satisfy the Grassmann-Plu¨cker’s equations of Proposition 33.29. Therefore, the map iG embeds the Grassmannian G(p,n) as an algebraic variety in defined by equations of degree 2.
 根据其PLU–KER坐标（λi），每个点都由被视为齐次坐标的PLU–KER坐标（λi）定义。对应于与可分解交替p张量相关的一维空间的点是坐标满足格拉斯曼-普卢克命题33.29方程的点。因此，map ig将grassmannian g（p，n）嵌入到由2次方程定义的代数变量中。

We can replace the field R by C in the above reasoning and we obtain an embedding of the complex Grassmannian GC(p,n) as an algebraic variety in defined by equations of degree 2.
 在上述推理中，我们可以用C来代替R域，得到了复数格拉斯曼GC（P，N）的嵌入，它是由2次方程定义的代数变量。

In particular, if n = 4 and p = 2, the equation
 特别是，如果n=4，p=2，则方程式

λ12λ34 − λ13λ24 + λ14λ23 = 0
 λ12λ34−λ13λ24+λ14λ23=0

is the homogeneous equation of a quadric in CP5 known as the Klein quadric. The points on this quadric are in one-to-one correspondence with the lines in CP3.
 是CP5中二次曲面的齐次方程，称为克莱恩二次曲面。二次曲面上的点与CP3中的直线一一对应。

There is also a simple algebraic criterion to decide whether the smallest subspaces U and V associated with two nonzero decomposable vectors u1 ∧ ··· ∧ up and v1 ∧ ··· ∧ vq have a nontrivial intersection.
 也有一个简单的代数准则来决定最小的子空间u和v是否与两个非零可分解向量u1··········································

Proposition 33.31. Let E be any n-dimensional vector space over a field K, and let U and V be the smallest subspaces of E associated with two nonzero decomposable vectors u = u1 ∧ ··· ∧ up ∈ Vp U and v = v1 ∧ ··· ∧ vq ∈ Vq V . The following properties hold:
 提案33.31。设e为k域上的任意n维向量空间，设u和v为e的最小子空间，与两个非零可分解向量u=u1································vq V相关。以下属性保留：

*(1)*     *We have U* ∩ *V* = (0) *iff u* ∧ *v* = 06     *.*

*(2)*     *If U* ∩ *V* = (0)*, then U* + *V is the least subspace associated with u* ∧ *v.*

*Proof.* Assume *U* ∩ *V* = (0). We know by Corollary 33.26 that (*u*1*,...,up*) is a basis of *U* and (*v*1*,...,vq*) is a basis of *V* . Since *U* ∩*V* = (0), (*u*1*,...,up,v*1*,...,vq*) is a basis of *U* +*V* , and by Proposition 33.8, we have

​                                                               *u* ∧ *v* = *u*1 ∧ ··· ∧ *u**p* ∧ *v*1 ∧ ··· ∧ *v**q* = 06    *.*

This also proves (2).

33.10.向量值交替形式

相反，假设dim（u v）≥1。选取w=u v的基（w1，…，w r），并将此基扩展到u的基（w1，…，wr，wr+1，…，wp）和v的基（w1，…，wr，wp+1，…，wp+q-r）。由推论33.26，（u1，…，up）也是u的基础，所以

U1·····向上=AW1···················Wp

对于某些a∈k，（v1，…，vq）也是v的基础，所以

v1······································

对于某些b∈k，因此

U V=U1·····向上V1···VQ=0

因为它含有一些重复的wi，1≤i≤r。

作为命题33.31的一个应用，考虑RP3中的两条投影线d1和d2，这意味着d1和d2对应于r4中的两个2平面，因此，通过命题33.30，到中的两点。这两个点对应于2个向量z=a1,2e1 e2+a1,3e1 e3+a1,4e1 e4+a2,3e2 e3+a2,4e2 e4+a3,4e3 e4和

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image002.gif)

其plu–cker坐标（其中ai，j=λij）满足方程

λ12λ34−λ13λ24+λ14λ23=0

Klein二次曲面，d1和d2相交iff z z0=0 iff

.

注意，对于d1固定，这是一个线性条件。这一事实对于解决涉及直线交叉的问题非常有帮助。一个著名的问题是找出rp3中有多少行在一般位置上与四个给定行相交。答案最多是2。

# 33.10向量值交替形式

本节的目的是介绍理解向量值微分形式所需的技术背景，特别是在李代数中自然出现取其值的微分形式的李群情况下。

在这一部分中，假设向量空间e具有有限维。我们知道在交替的n型图和交替的多行图之间有一个典型的同构vn（e）=altn（e；k）。与一般张量一样，命题33.5、32.17和33.10提供的同构，即

altn（e；f）=hom hom

产生一个标准同构

中高音

我们将其记录为推论。

推论33.32。对于任何有限维向量空间e和任何向量空间f，我们都有一个正则同构。

中高音

注意f可能有无穷大的维数。这种同构允许我们把Vn（e）f中的张量看作矢量值交替形式，这一观点在微分几何中很有用。如果（f1，…，fr）是f的基，则每个张量ω∈vn（e）f都可以写成某种线性组合。

，

对于αi∈vn（e），我们也让

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image004.gif)

给定三个向量空间f，g，h，如果我们有一些双线性映射Φ：f×g→h，那么我们可以定义一个乘法运算。

Φ：^（E；F）×^（E；G）→^（E；H）

如下：对于每对（m，n），我们定义乘法

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image006.gif)

33.10.向量值交替形式

通过

ωΦη=（αf）Φ（βg）=（αβ）Φ（f，g）。

如第33.5节（H.Cartan[35]之后）所述，我们还可以定义乘法

Φ：altm（e；f）×altn（e；g）−→altm+n（e；h）

直接在交替多行图上如下：对于f∈altm（e；f）和g∈altn（e；g），

，

式中，shuffle（m，n）由所有（m，n）-“shuffles”组成；即，置换σof 1，…m+n，这样，σ（1）<······<σ（m）和σ（m+1）<······<σ（m+n）。

特殊情况下，f=g=h是李代数，Φ（a，b）=[a，b]是f的李括号。在这种情况下，使用f的基（f1，…，fr），如果我们写ω=piαi fi和η=pjβj_fj，我们得到

ωΦη=[ω，η]=xαiβj[fi，fj]。

我，J

通常用[ω，η]表示ω_Φη（不幸的是，括号符号过载）。因此，

[η，ω]=（−1）mn+1[ω，η]。

一般来说，关于Φ可以说的不多，除非Φ有一些附加的性质。特别是，_Φ通常不关联。

我们现在使用向量值交替形式来概括命题的μ映射

33.14并通过定义地图来概括32.17号提案

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image008.gif)

在发电机上

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image010.gif)

与，和f∈f。

提案33.33。地图

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image012.gif)

定义如上是一个典型的同构每N≥0。此外，给定任意三个向量空间，f，g，h和任意双线性映射Φ：f×g→h，对于所有ω∈（vn（e））f和所有η∈（vn（e））g，_h（ωΦη）=_f（ω）Φ_（η）。

证据。因为我们已经知道（vn（e）f和altn（e；f）是同构的，所以足以证明μf将（vn（e）f的一些基映射到线性独立元素。选取一些基（i 1，…，pe 1，…，eand ip）=inne，在fv中形成（和（fj）j∈j的基。然后我们知道向量n（e）f。如果我们有一个线性相关性，其中

xλi，jμf（e i fj）=0，

我，J

将上述组合应用于每一个（ei1，…，ein）（i=i1，…，in，i1<·····<in），我们得到线性组合。

X

λi，jfj=0，

J

通过fj的线性独立性，我们得到了所有i和所有j的λi，j=0。因此，

）是线性独立的，我们完成了。命题的第二部分是用一个简单的计算来检验的。

下面的命题将有助于处理向量值微分形式。

提案33.34。如果（e1，…，ep）是e的任何基，那么每个元素ω∈（vn（e）f都可以用一种独特的方式写为

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image014.gif)

其中，定义见第33.2节。

证据。因为，根据命题33.7，e i构成了vn（e）的基础，e i f形式的元素（vn（e）f。现在，如果我们将μf（ω）应用于（e i1，…，e in），其中i=i1，…，in 1，…，p，我们得到

.

因此，fi由f唯一确定。

命题33.34也可以用交替的多行图来表示，这一事实对于处理微分形式是有用的。

推论33.35。将产品·：altn（e；r）×f→altn（e；f）定义为：对于所有ω∈altn（e；r）和所有f∈f，

（ω·f）（u1，…，un）=ω（u1，…，un）f，

对于所有的u1，…，un e，那么对于形式的每个ω（vn（e））f

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image016.gif)

我们有

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image018.gif)

33.11.问题

则命题33.34得出以下结果。

提案33.36。如果（e1，…，ep）是e的任何基，那么每个元素ω∈altn（e；f）都可以用一种独特的方式写成

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image020.gif)

其中e i的定义见第33.2节。

# 33.11问题

问题33.1。完成命题33.1（2）证明中使用的归纳论点。

问题33.2。证明33.2号提案。

问题33.3。证明33.9号提案。

问题33.4。证明第33.4节中（）给出的配对是非退化的。

问题33.5。假设ia是由u u∈v 2形式的所有张量产生的双面理想。证明这一点

.

问题33.6。完成33.12号提案的归纳证明。

问题33.7。证明了以下引理：如果v是一个dim（v）≤3的向量空间，那么αα=0，只要αv（v）。

问题33.8。证明33.13号提案。

问题33.9。给定两个梯度代数e和f，将e b f定义为向量空间e f，但用下式给出的斜交交换乘法

（a b）（c d）=（-1）deg（b）deg（c）（ac）（bd）、

其中a∈em，b∈fp，c∈en，d∈fq。展示一下

^（e_f）b（f）。

问题33.10。如果h−，−i表示v上的内积，回想一下我们在vk v上定义了一个内积，也表示h−，−i，通过设置

hu1····UK，v1·····VKI=DET（hui，vji）

对于所有的ui，v i∈v，并通过双线性扩展h−、−i。

证明如果（e1，…，en）是v的正态基，那么由ei组成的vk v的基（其中i=i1，…，ik，1≤i1···································

问题33.11。展示一下

（u v）y z=u y（v y z），

当u∈v k e，v∈vp−k e，z∈vp+q e时。

问题33.12。证明33.18号提案的陈述（3）。

问题33.13。证明33.19号提案。同时证明身份

u y（x y）=（−1）s（u y x）y+x（u y）、

式中，u∈e，x∈vq+1−s e，y∈vs e.

问题33.14。使用格拉斯曼PLU–克尔方程证明，如果dim（e）=n，那么vn-1（e）中的每个张量都是可分解的。问题33.15。回想一下地图

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image022.gif)

在生成器上定义

![img](file:///C:/Users/ADMINI~1/AppData/Local/Temp/msohtmlclip1/01/clip_image024.gif)

与，和f∈f。

给定任意三个向量空间f，g，h和任意双线性映射Φ：f×g→h，对于所有ω∈（vn（e））f和所有η∈（vn（e））g证明

_h（ωΦη）=_f（ω）_Φg（η）。


 